"use client";
import {forwardRef,useState} from "react";
import {useRouter} from "next/navigation";
import {ArrowLeft,ArrowRight,Check} from "lucide-react";
import {AnimatePresence,motion,useReducedMotion} from "framer-motion";
import {useFinanceStore} from "@/lib/store";
import {AddDebtDialog} from "@/components/add-debt-dialog";
import {OnboardingIncomeDialog} from "@/components/onboarding-income-dialog";
import {AddBudgetDialog} from "@/components/add-budget-dialog";
import {formatCurrency} from "@/lib/utils";
import {BrandMark} from "@/components/brand-logo";
import {trackEventSafely} from "@/lib/analytics/client";
const copy=[["Welcome to ZeroDebt","Let’s build your debt-free plan."],["What debt do you want to clear first?","Add the debt that matters most. You can edit or add more later."],["How much comes in each month?","Add regular income so we can estimate what is available for debt."],["What do you need to spend each month?","Start with essentials—not every small purchase."],["Your debt-free plan","Here is your starting point based on what you entered."]] as const;
export default function OnboardingPage(){
 const router=useRouter(),state=useFinanceStore(),saved=state.settings.onboarding;
 const[step,setStep]=useState(Math.min(5,Math.max(1,saved?.currentStep||1))),[busy,setBusy]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState(""),[direction,setDirection]=useState(1),reduceMotion=useReducedMotion();
 const income=state.incomes.reduce((s,i)=>s+i.expectedMonthly,0),essential=state.expenses.reduce((s,e)=>s+e.budgeted,0),remaining=state.debts.reduce((s,d)=>s+d.balance,0),power=Math.max(0,income-essential),next=[...state.debts].filter(d=>d.balance>0).sort((a,b)=>(b.rate||0)-(a.rate||0)||a.balance-b.balance)[0],months=power&&remaining?Math.ceil(remaining/power):0;
 const persist=async(body:Record<string,unknown>)=>{const r=await fetch('/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error('save')};
 const advance=async(skip=false)=>{setBusy(true);setError('');setSuccess('');try{if(step===2&&!state.debts.length&&!skip)throw new Error('debt');if(step===3&&!income&&!skip)throw new Error('income');if(step===4&&!state.expenses.length&&!skip)throw new Error('expenses');const nextStep=Math.min(5,step+1),flags=skip?{}:step===2?{debtCompleted:true}:step===3?{incomeCompleted:true}:step===4?{expensesCompleted:true}:{};await persist({onboardingStep:nextStep,...flags});useFinanceStore.setState(s=>({settings:{...s.settings,onboarding:{...s.settings.onboarding,currentStep:nextStep,...flags}}}));setDirection(1);setStep(nextStep)}catch(e){setError(e instanceof Error&&e.message==='save'?'We could not save your progress. Check your connection and try again.':'Add an entry or choose Skip for now.')}finally{setBusy(false)}};
 const finish=async()=>{setBusy(true);setError('');try{await persist({onboarded:true,onboardingStep:5,payoffSeen:true});useFinanceStore.setState(s=>({settings:{...s.settings,onboarded:true,onboarding:{...s.settings.onboarding,currentStep:5,payoffSeen:true}}}));trackEventSafely('onboarding_completed',{steps:5},'onboarding');router.replace('/overview');router.refresh()}catch{setError('We could not complete onboarding. Try again.')}finally{setBusy(false)}};
 const savedMessage=(message:string)=>{setError('');setSuccess(message)};
 return <main className="onboarding-shell mx-auto min-h-dvh w-full max-w-xl px-5 pb-10 pt-[max(2rem,env(safe-area-inset-top))]">
  <header className="flex items-center justify-between"><div className="flex items-center gap-2 font-bold"><BrandMark className="h-9 w-9 rounded-xl"/>ZeroDebt</div><button type="button" onClick={async()=>{setSuccess('Your progress is saved.');await new Promise(resolve=>setTimeout(resolve,220));await fetch('/auth/logout',{method:'POST'});router.replace('/auth');router.refresh()}} className="tap-target px-2 text-sm font-semibold text-muted-foreground">Save & leave</button></header>
  <div role="progressbar" aria-valuemin={1} aria-valuemax={5} aria-valuenow={step} aria-label={`Step ${step} of 5`} className="mt-10 flex gap-2">{[1,2,3,4,5].map(i=><motion.span key={i} aria-current={i===step?'step':undefined} animate={{backgroundColor:i<=step?'hsl(var(--primary))':'hsl(var(--secondary))',scaleX:i===step?1:.96}} transition={{duration:reduceMotion?0:.2}} className="h-1.5 flex-1 rounded-full"/>)}</div>
  <AnimatePresence mode="wait" custom={direction} initial={false}><motion.div key={step} custom={direction} initial={reduceMotion?false:{opacity:0,x:direction*12}} animate={{opacity:1,x:0}} exit={reduceMotion?undefined:{opacity:0,x:direction*-10}} transition={{duration:reduceMotion?0:.21,ease:[.16,1,.3,1]}}><header className="mt-9"><h1 className="text-balance text-3xl font-bold tracking-tight">{copy[step-1][0]}</h1><p className="mt-3 leading-7 text-muted-foreground">{copy[step-1][1]}</p>{(step===1||step===5)&&<p className="mt-3 text-sm font-semibold text-primary">A brighter tomorrow starts at zero.</p>}</header>
  <section className="mt-8">{step===1&&<div className="rounded-2xl bg-primary/10 p-6"><p className="font-semibold">In a few minutes, you’ll know:</p>{["Your Freedom Number","Your monthly payoff power","The next debt to focus on"].map(x=><p key={x} className="mt-3 flex gap-2 text-sm"><Check className="h-5 w-5 text-primary"/>{x}</p>)}</div>}{step===2&&<div className="space-y-3"><AddDebtDialog onSaved={()=>savedMessage('Debt added')}><Action>Add debt</Action></AddDebtDialog><p className="text-sm text-muted-foreground">You can add more later.</p>{state.debts.map(d=><Row key={d.id} label={d.name} value={formatCurrency(d.balance,state.settings.currency)}/>)}{!state.debts.length&&<button type="button" disabled={busy} onClick={async()=>{setBusy(true);setError('');if(await state.loadDemoData()){await persist({onboardingStep:5,debtCompleted:true,incomeCompleted:true,expensesCompleted:true});setDirection(1);setStep(5)}else setError('Sample data can only be added to an empty workspace.');setBusy(false)}} className="tap-target w-full rounded-xl border border-border bg-card px-5 font-semibold">Try with sample data</button>}</div>}{step===3&&<div className="space-y-3"><OnboardingIncomeDialog onSaved={()=>savedMessage('Income added')}><Action>Add monthly income</Action></OnboardingIncomeDialog><p className="text-sm text-muted-foreground">Use your usual monthly amount.</p><Row label="Monthly income" value={formatCurrency(income,state.settings.currency)}/></div>}{step===4&&<div className="space-y-3"><AddBudgetDialog onSaved={()=>savedMessage('Expense added')}><Action>Add essential expense</Action></AddBudgetDialog><p className="text-sm text-muted-foreground">Just add the essentials for now.</p><Row label="Essential expenses" value={formatCurrency(essential,state.settings.currency)}/></div>}{step===5&&<div className="space-y-3">{[["Your Freedom Number",formatCurrency(remaining,state.settings.currency)],["Monthly Payoff Power",formatCurrency(power,state.settings.currency)],["Next Debt to Attack",next?.name||'No debt added'],["Estimated Debt-Free Date",months?new Date(new Date().getFullYear(),new Date().getMonth()+months,1).toLocaleDateString(undefined,{month:'long',year:'numeric'}):'Add monthly cash flow']].map(([label,value],index)=><motion.div key={label} initial={reduceMotion?false:{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{delay:reduceMotion?0:index*.09,duration:.24}} className={index===0?'rounded-2xl bg-primary p-6 text-primary-foreground':'mobile-card p-4'}><p className={index===0?'text-sm opacity-75':'text-sm text-muted-foreground'}>{label}</p><p className={`${index===0?'mt-3 text-4xl':'mt-1 text-xl'} font-bold`}>{value}</p></motion.div>)}<p className="text-xs text-muted-foreground">Payoff estimates are projections based on the information you’ve entered.</p></div>}</section></motion.div></AnimatePresence>
  {success&&<motion.p initial={reduceMotion?false:{opacity:0,y:5}} animate={{opacity:1,y:0}} role="status" className="mt-5 flex items-center gap-2 rounded-xl bg-primary/10 p-3 text-sm font-medium text-primary"><Check className="h-4 w-4"/>{success}</motion.p>}{error&&<p role="alert" className="mt-5 rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}
  <footer className="mt-9 flex flex-wrap gap-3">{step>1&&<button type="button" onClick={()=>{setDirection(-1);setStep(step-1);setError('');setSuccess('')}} className="tap-target grid place-items-center rounded-xl border border-border px-4" aria-label="Previous step"><ArrowLeft/></button>}{step>1&&step<5&&<button type="button" disabled={busy} onClick={()=>advance(true)} className="tap-target px-3 text-sm font-semibold text-muted-foreground">Skip for now</button>}<button type="button" disabled={busy} onClick={()=>step===5?finish():advance()} className="tap-target flex flex-1 items-center justify-center gap-2 rounded-xl bg-primary px-5 font-semibold text-primary-foreground transition duration-150 active:scale-[.98] disabled:transform-none">{busy?'Saving…':step===5?'See My Dashboard':'Continue'}<ArrowRight className="h-4 w-4"/></button></footer>
 </main>
}
const Action=forwardRef<HTMLButtonElement,React.ButtonHTMLAttributes<HTMLButtonElement>>(function Action({children,className,...props},ref){return <button ref={ref} type="button" {...props} className={`tap-target w-full rounded-xl bg-primary px-5 font-semibold text-primary-foreground ${className||''}`}>{children}</button>});
function Row({label,value}:{label:string;value:string}){return <div className="mobile-card flex items-center justify-between gap-4 p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="text-right font-semibold">{value}</p></div>}
