"use client";
import {forwardRef,useState} from "react";
import {useRouter} from "next/navigation";
import {ArrowLeft,ArrowRight,Check,TrendingDown} from "lucide-react";
import {useFinanceStore} from "@/lib/store";
import {AddDebtDialog} from "@/components/add-debt-dialog";
import {OnboardingIncomeDialog} from "@/components/onboarding-income-dialog";
import {AddBudgetDialog} from "@/components/add-budget-dialog";
import {formatCurrency} from "@/lib/utils";
const copy=[["Welcome to ZeroDebt","Let’s build your debt-free plan."],["What debt do you want to clear first?","Add the debt that matters most. You can edit or add more later."],["How much comes in each month?","Add regular income so we can estimate what is available for debt."],["What do you need to spend each month?","Start with essentials—not every small purchase."],["Your debt-free plan","Here is your starting point based on what you entered."]] as const;
export default function OnboardingPage(){
 const router=useRouter(),state=useFinanceStore(),saved=state.settings.onboarding;
 const[step,setStep]=useState(Math.min(5,Math.max(1,saved?.currentStep||1))),[busy,setBusy]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const income=state.incomes.reduce((s,i)=>s+i.expectedMonthly,0),essential=state.expenses.reduce((s,e)=>s+e.budgeted,0),remaining=state.debts.reduce((s,d)=>s+d.balance,0),power=Math.max(0,income-essential),next=[...state.debts].filter(d=>d.balance>0).sort((a,b)=>(b.rate||0)-(a.rate||0)||a.balance-b.balance)[0],months=power&&remaining?Math.ceil(remaining/power):0;
 const persist=async(body:Record<string,unknown>)=>{const r=await fetch('/api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw new Error('save')};
 const advance=async(skip=false)=>{setBusy(true);setError('');setSuccess('');try{if(step===2&&!state.debts.length&&!skip)throw new Error('debt');if(step===3&&!income&&!skip)throw new Error('income');if(step===4&&!state.expenses.length&&!skip)throw new Error('expenses');const nextStep=Math.min(5,step+1),flags=skip?{}:step===2?{debtCompleted:true}:step===3?{incomeCompleted:true}:step===4?{expensesCompleted:true}:{};await persist({onboardingStep:nextStep,...flags});useFinanceStore.setState(s=>({settings:{...s.settings,onboarding:{...s.settings.onboarding,currentStep:nextStep,...flags}}}));setStep(nextStep)}catch(e){setError(e instanceof Error&&e.message==='save'?'We could not save your progress. Check your connection and try again.':'Add an entry or choose Skip for now.')}finally{setBusy(false)}};
 const finish=async()=>{setBusy(true);setError('');try{await persist({onboarded:true,onboardingStep:5,payoffSeen:true});useFinanceStore.setState(s=>({settings:{...s.settings,onboarded:true,onboarding:{...s.settings.onboarding,currentStep:5,payoffSeen:true}}}));router.replace('/overview');router.refresh()}catch{setError('We could not complete onboarding. Try again.')}finally{setBusy(false)}};
 const savedMessage=(message:string)=>{setError('');setSuccess(message)};
 return <main className="onboarding-shell mx-auto min-h-dvh w-full max-w-xl px-5 pb-10 pt-[max(2rem,env(safe-area-inset-top))]">
  <header className="flex items-center justify-between"><div className="flex items-center gap-2 font-bold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-primary text-primary-foreground"><TrendingDown className="h-5 w-5"/></span>ZeroDebt</div><form action="/auth/logout" method="post"><button type="submit" className="tap-target px-2 text-sm font-semibold text-muted-foreground">Save & leave</button></form></header>
  <div role="progressbar" aria-valuemin={1} aria-valuemax={5} aria-valuenow={step} aria-label={`Step ${step} of 5`} className="mt-10 flex gap-2">{[1,2,3,4,5].map(i=><span key={i} aria-current={i===step?'step':undefined} className={`h-1.5 flex-1 rounded-full transition-colors duration-200 ${i<=step?'bg-primary':'bg-secondary'}`}/>)}</div><header className="mt-9"><h1 className="text-balance text-3xl font-bold tracking-tight">{copy[step-1][0]}</h1><p className="mt-3 leading-7 text-muted-foreground">{copy[step-1][1]}</p></header>
  <section className="mt-8">{step===1&&<div className="rounded-2xl bg-primary/10 p-6"><p className="font-semibold">In a few minutes, you’ll know:</p>{["Your Freedom Number","Your monthly payoff power","The next debt to focus on"].map(x=><p key={x} className="mt-3 flex gap-2 text-sm"><Check className="h-5 w-5 text-primary"/>{x}</p>)}</div>}{step===2&&<div className="space-y-3"><AddDebtDialog onSaved={()=>savedMessage('Debt saved.')}><Action>Add debt</Action></AddDebtDialog>{state.debts.map(d=><Row key={d.id} label={d.name} value={formatCurrency(d.balance,state.settings.currency)}/>)}{!state.debts.length&&<button type="button" disabled={busy} onClick={async()=>{setBusy(true);setError('');if(await state.loadDemoData()){await persist({onboardingStep:5,debtCompleted:true,incomeCompleted:true,expensesCompleted:true});setStep(5)}else setError('Sample data can only be added to an empty workspace.');setBusy(false)}} className="tap-target w-full rounded-xl border border-border bg-card px-5 font-semibold">Try with sample data</button>}</div>}{step===3&&<div className="space-y-3"><OnboardingIncomeDialog onSaved={()=>savedMessage('Monthly income saved.')}><Action>Add monthly income</Action></OnboardingIncomeDialog><Row label="Income recorded" value={formatCurrency(income,state.settings.currency)}/></div>}{step===4&&<div className="space-y-3"><AddBudgetDialog onSaved={()=>savedMessage('Essential expense saved.')}><Action>Add essential expense</Action></AddBudgetDialog><p className="text-sm text-muted-foreground">Housing, groceries, transport, utilities, insurance, education, and health.</p><Row label="Essentials recorded" value={formatCurrency(essential,state.settings.currency)}/></div>}{step===5&&<div className="space-y-3"><div className="rounded-2xl bg-primary p-6 text-primary-foreground"><p className="text-sm opacity-75">Your Freedom Number</p><p className="mt-3 text-4xl font-bold">{formatCurrency(remaining,state.settings.currency)}</p><p className="mt-5 text-sm opacity-75">Monthly Payoff Power</p><p className="mt-1 text-2xl font-bold">{formatCurrency(power,state.settings.currency)}</p></div><div className="mobile-card divide-y divide-border"><Row label="Suggested strategy" value="Avalanche"/><Row label="Next debt to attack" value={next?.name||'No debt added'}/><Row label="Estimated debt-free date" value={months?new Date(new Date().getFullYear(),new Date().getMonth()+months,1).toLocaleDateString(undefined,{month:'long',year:'numeric'}):'Add monthly cash flow'}/></div><p className="text-xs text-muted-foreground">Payoff estimates are projections based on the information you’ve entered.</p></div>}</section>
  {success&&<p role="status" className="mt-5 rounded-xl bg-primary/10 p-3 text-sm font-medium text-primary">{success}</p>}{error&&<p role="alert" className="mt-5 rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}
  <footer className="mt-9 flex flex-wrap gap-3">{step>1&&<button type="button" onClick={()=>{setStep(step-1);setError('');setSuccess('')}} className="tap-target grid place-items-center rounded-xl border border-border px-4" aria-label="Previous step"><ArrowLeft/></button>}{step>1&&step<5&&<button type="button" disabled={busy} onClick={()=>advance(true)} className="tap-target px-3 text-sm font-semibold text-muted-foreground">Skip for now</button>}<button type="button" disabled={busy} onClick={()=>step===5?finish():advance()} className="tap-target flex flex-1 items-center justify-center gap-2 rounded-xl bg-primary px-5 font-semibold text-primary-foreground">{busy?'Saving…':step===5?'See My Dashboard':'Continue'}<ArrowRight className="h-4 w-4"/></button></footer>
 </main>
}
const Action=forwardRef<HTMLButtonElement,React.ButtonHTMLAttributes<HTMLButtonElement>>(function Action({children,className,...props},ref){return <button ref={ref} type="button" {...props} className={`tap-target w-full rounded-xl bg-primary px-5 font-semibold text-primary-foreground ${className||''}`}>{children}</button>});
function Row({label,value}:{label:string;value:string}){return <div className="mobile-card flex items-center justify-between gap-4 p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="text-right font-semibold">{value}</p></div>}
