import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import manifest from "../app/manifest";

const source=(path:string)=>readFileSync(new URL(`../${path}`,import.meta.url),"utf8");
describe("ZeroDebt public experience",()=>{
  it("keeps the root landing page public and protects app routes",()=>{const middleware=source("lib/supabase/middleware.ts");expect(middleware).toContain("path === '/'");expect(middleware).toContain("url.pathname = '/auth'")});
  it("connects landing calls to action to authentication",()=>{const landing=source("app/page.tsx");expect(landing).toContain('href="/auth"');expect(landing).toContain("Start Your Debt-Free Journey")});
  it("ships installable standalone metadata without API caching",()=>{const value=manifest();expect(value.name).toBe("ZeroDebt");expect(value.display).toBe("standalone");expect(value.start_url).toBe("/overview");expect(value.scope).toBe("/");expect(value.icons).toEqual(expect.arrayContaining([expect.objectContaining({sizes:"192x192"}),expect.objectContaining({sizes:"512x512",purpose:"maskable"})]));expect(source("app/manifest.ts")).not.toMatch(/serviceWorker|api\/workspace/i)});
  it("hides Google sign-in unless explicitly configured",()=>{expect(source("app/auth/auth-form.tsx")).toContain("NEXT_PUBLIC_GOOGLE_AUTH_ENABLED==='true'")});
  it("keeps valid currency out of onboarding",()=>{expect(source("app/onboarding/page.tsx")).not.toMatch(/select default currency|base currency/i)});
  it("persists and resumes onboarding from the server profile",()=>{const onboarding=source("app/onboarding/page.tsx"),settings=source("app/api/settings/route.ts");expect(onboarding).toContain("saved?.currentStep||1");expect(onboarding).toContain("onboardingStep:nextStep");expect(settings).toContain("onboarding_step")});
  it("requires finance data or an explicit skip before completing input steps",()=>{const onboarding=source("app/onboarding/page.tsx");expect(onboarding).toContain("!state.debts.length&&!skip");expect(onboarding).toContain("!income&&!skip");expect(onboarding).toContain("!state.expenses.length&&!skip")});
  it("forwards dialog trigger props from onboarding action buttons",()=>{const onboarding=source("app/onboarding/page.tsx");expect(onboarding).toContain("forwardRef<HTMLButtonElement");expect(onboarding).toContain("ref={ref}");expect(onboarding).toContain("{...props}");expect(onboarding).toContain('type="button"')});
  it("saves onboarding income through the authenticated income API",()=>{const dialog=source("components/onboarding-income-dialog.tsx");expect(dialog).toContain('fetch("/api/incomes"');expect(dialog).toContain('Saving income…');expect(dialog).toContain('role="alert"')});
  it("persists debt and essential expenses before updating client state",()=>{expect(source("components/add-debt-dialog.tsx")).toContain("fetch('/api/debts'");expect(source("components/add-budget-dialog.tsx")).toContain("fetch('/api/expenses'")});
  it("does not mark skipped onboarding data as completed",()=>{expect(source("app/onboarding/page.tsx")).toContain("flags=skip?{}")});
  it("opens center actions only after closing their parent sheet",()=>{const nav=source("components/sidebar-nav.tsx");expect(nav).toContain("setSheetOpen(false);window.setTimeout(open,180)");for(const action of ["setQuickEntryOpen(true)","setPaymentOpen(true)","setTransactionType('expense')","setTransactionType('income')","setTransactionType('transfer')","setDebtOpen(true)","setAccountOpen(true)","setGoalOpen(true)"])expect(nav).toContain(action)});
  it("keeps debt submission single-flight and server authoritative",()=>{const debt=source("components/add-debt-dialog.tsx");expect(debt).toContain("disabled={saving}");expect(debt).toContain("fetch('/api/debts'");expect(debt).toContain("useFinanceStore.setState")});
  it("shows the transaction-adjusted available balance and account-count copy",()=>{const overview=source("app/overview/page.tsx");expect(overview).toContain("calculateAvailableBalance(accounts,transactions,settings)");expect(overview).toContain("Across ${available.accountCount}");expect(overview).toContain("Add an account to see what you have available.")});
  it("offers the existing goal flow from the Goals empty state",()=>{const goals=source("app/goals/page.tsx");expect(goals).toContain("Add your first goal and start tracking your progress.");expect(goals).toContain("<AddGoalDialog>");expect(goals).toContain("Create your first goal")});
  it("uses the visual viewport for Android keyboard-safe finance sheets",()=>{const dialog=source("components/ui/dialog.tsx"),styles=source("app/globals.css");expect(dialog).toContain("window.visualViewport");expect(dialog).toContain("--visual-viewport-height");expect(styles).toContain("--visual-viewport-bottom");expect(styles).toContain("overscroll-behavior: contain")});
  it("keeps finance-sheet headers and save areas sticky and safe",()=>{const styles=source("app/globals.css");expect(styles).toContain(".sheet-action-footer");expect(styles).toContain("position: sticky");for(const file of ["components/add-budget-dialog.tsx","components/add-debt-dialog.tsx","components/add-account-dialog.tsx","components/add-goal-dialog.tsx","components/add-transaction-dialog.tsx","components/record-debt-payment-dialog.tsx","components/quick-entry-dialog.tsx"])expect(source(file)).toMatch(/bottom-sheet|finance-sheet/)});
  it("adapts Quick Entry review fields and clears incompatible values",()=>{const quick=source("components/quick-entry-dialog.tsx");expect(quick).toContain("changeType");expect(quick).toContain("category:type==='debt_payment'?'Debt Payment':null,debt_id:null");expect(quick).toContain("Income source");expect(quick).toContain("Deposit account");expect(quick).toContain("Pay from account");expect(quick).toContain("Confirm Payment");expect(quick).toContain("AnimatePresence mode=\"wait\"")});
  it("uses a validated emerald goal flow and controlled categories",()=>{const goal=source("components/add-goal-dialog.tsx");for(const category of ["Emergency Fund","Home","Car","Travel","Education","Family","Business","Health","Other"])expect(goal).toContain(`\"${category}\"`);expect(goal).toContain("target<=0");expect(goal).toContain("saved>target");expect(goal).toContain("inputMode=\"decimal\"");expect(goal).toContain("Create Goal");expect(goal).not.toContain("purple");expect(goal).not.toContain('value="0"')});
  it("hydrates a newly persisted goal without reloading",()=>{const goal=source("components/add-goal-dialog.tsx");expect(goal).toContain("fetch('/api/goals'");expect(goal).toContain("goals:[...state.goals,goal]");expect(goal).not.toContain("location.reload")});
  it("gates platform install guidance and remembers dismissal",()=>{const install=source("components/install-zero-debt.tsx");expect(install).toContain("beforeinstallprompt");expect(install).toContain("display-mode: standalone");expect(install).toContain("zerodebt-install-dismissed");expect(install).toContain("iphone|ipad|ipod")});
});
