import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import manifest from "../app/manifest";

const source=(path:string)=>readFileSync(new URL(`../${path}`,import.meta.url),"utf8");
describe("ZeroDebt public experience",()=>{
  it("keeps the root landing page public and protects app routes",()=>{const middleware=source("lib/supabase/middleware.ts");expect(middleware).toContain("path === '/'");expect(middleware).toContain("url.pathname = '/auth'")});
  it("connects landing calls to action to authentication",()=>{const landing=source("app/page.tsx");expect(landing).toContain('href="/auth"');expect(landing).toContain("Start Your Debt-Free Journey")});
  it("ships installable standalone metadata without API caching",()=>{const value=manifest();expect(value.name).toBe("ZeroDebt");expect(value.display).toBe("standalone");expect(value.start_url).toBe("/overview");expect(value.scope).toBe("/");expect(value.icons).toEqual(expect.arrayContaining([expect.objectContaining({sizes:"192x192"}),expect.objectContaining({sizes:"512x512",purpose:"maskable"})]));expect(source("app/manifest.ts")).not.toMatch(/serviceWorker|api\/workspace/i)});
  it("hides Google sign-in unless explicitly configured",()=>{expect(source("app/auth/auth-form.tsx")).toContain("NEXT_PUBLIC_GOOGLE_AUTH_ENABLED==='true'")});
  it("keeps valid currency out of onboarding",()=>{expect(source("app/onboarding/page.tsx")).not.toMatch(/select default currency|base currency/i)});
  it("persists and resumes onboarding from the server profile",()=>{const onboarding=source("app/onboarding/page.tsx"),settings=source("app/api/settings/route.ts");expect(onboarding).toContain("saved?.currentStep||1");expect(onboarding).toContain("onboardingStep:nextStep");expect(settings).toContain("onboarding_step")});
  it("requires finance data or an explicit skip before completing input steps",()=>{const onboarding=source("app/onboarding/page.tsx");expect(onboarding).toContain("!state.debts.length&&!skip");expect(onboarding).toContain("!income&&!skip");expect(onboarding).toContain("!state.expenses.length&&!skip")});
  it("forwards dialog trigger props from onboarding action buttons",()=>{const onboarding=source("app/onboarding/page.tsx");expect(onboarding).toContain("forwardRef<HTMLButtonElement");expect(onboarding).toContain("ref={ref}");expect(onboarding).toContain("{...props}");expect(onboarding).toContain('type="button"')});
  it("saves onboarding income through the authenticated income API",()=>{const dialog=source("components/onboarding-income-dialog.tsx");expect(dialog).toContain('fetch("/api/incomes"');expect(dialog).toContain('Saving income…');expect(dialog).toContain('role="alert"')});
  it("persists debt and essential expenses before updating client state",()=>{expect(source("components/add-debt-dialog.tsx")).toContain("fetch('/api/debts'");expect(source("components/add-budget-dialog.tsx")).toContain("fetch('/api/expenses'")});
  it("does not mark skipped onboarding data as completed",()=>{expect(source("app/onboarding/page.tsx")).toContain("flags=skip?{}")});
  it("opens center actions only after closing their parent sheet",()=>{const nav=source("components/sidebar-nav.tsx");expect(nav).toContain("setSheetOpen(false);window.setTimeout(open,180)");for(const action of ["setQuickEntryOpen(true)","setPaymentOpen(true)","setTransactionType('expense')","setTransactionType('income')","setTransactionType('transfer')","setDebtOpen(true)","setAccountOpen(true)","setGoalOpen(true)"])expect(nav).toContain(action)});
  it("keeps debt submission single-flight and server authoritative",()=>{const debt=source("components/add-debt-dialog.tsx");expect(debt).toContain("disabled={saving}");expect(debt).toContain("fetch('/api/debts'");expect(debt).toContain("useFinanceStore.setState")});
  it("shows the transaction-adjusted available balance and account-count copy",()=>{const overview=source("app/overview/page.tsx");expect(overview).toContain("calculateAvailableBalance(accounts,transactions,settings)");expect(overview).toContain("Across ${available.accountCount}");expect(overview).toContain("Add an account to see what you have available.")});
  it("gates platform install guidance and remembers dismissal",()=>{const install=source("components/install-zero-debt.tsx");expect(install).toContain("beforeinstallprompt");expect(install).toContain("display-mode: standalone");expect(install).toContain("zerodebt-install-dismissed");expect(install).toContain("iphone|ipad|ipod")});
});
