import {APP_URL} from '@/lib/app-url';

const endpoint=(method:string)=>{const token=process.env.TELEGRAM_BOT_TOKEN;if(!token)throw new Error('Telegram is not configured');return `https://api.telegram.org/bot${token}/${method}`};
async function call(method:string,body:Record<string,unknown>){const response=await fetch(endpoint(method),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});if(!response.ok){const result=await response.json().catch(()=>null) as {description?:string}|null;throw new Error(`Telegram ${method} failed${result?.description?`: ${result.description}`:''}`)}}
export async function downloadTelegramFile(fileId:string,maxBytes:number){const token=process.env.TELEGRAM_BOT_TOKEN;if(!token)throw new Error('Telegram is not configured');const meta=await fetch(endpoint('getFile'),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({file_id:fileId}),signal:AbortSignal.timeout(10000)});const payload=await meta.json() as {ok?:boolean;result?:{file_path?:string;file_size?:number}};if(!meta.ok||!payload.ok||!payload.result?.file_path)throw new Error('telegram_file_unavailable');if((payload.result.file_size??0)>maxBytes)throw new Error('image_too_large');const response=await fetch(`https://api.telegram.org/file/bot${token}/${payload.result.file_path}`,{signal:AbortSignal.timeout(15000)});if(!response.ok)throw new Error('telegram_file_unavailable');const bytes=await response.arrayBuffer();if(bytes.byteLength>maxBytes)throw new Error('image_too_large');return {bytes,contentType:(response.headers.get('content-type')??'application/octet-stream').split(';')[0].trim().toLowerCase()};}
export const sendMessage=(chatId:number,text:string,replyMarkup?:Record<string,unknown>)=>call('sendMessage',{chat_id:chatId,text,...(replyMarkup?{reply_markup:replyMarkup}:{})});
export const answerCallback=(id:string,text?:string)=>call('answerCallbackQuery',{callback_query_id:id,...(text?{text}:{})});
export const editMessage=(chatId:number,messageId:number,text:string)=>call('editMessageText',{chat_id:chatId,message_id:messageId,text});
export const draftKeyboard=(id:string,payment:boolean)=>({inline_keyboard:[[{text:payment?'Confirm Payment':'Confirm',callback_data:`qe_confirm:${id}`}],[{text:'Edit',callback_data:`qe_edit:${id}`},{text:'Cancel',callback_data:`qe_cancel:${id}`}]]});
export const financeKeyboard=()=>({inline_keyboard:[[{text:'Open Finance',url:`${APP_URL}/telegram`}]]});
