import { createAdminClient } from '@/lib/supabase/admin';
import { parseQuickEntry } from '@/lib/quick-entry/parser';
import { ambiguousMessage,draftMessage,helpMessage } from './messages';
import { answerCallback,draftKeyboard,editMessage,financeKeyboard,sendMessage } from './api';
import { hashLinkToken,validDraftCallback } from './security';
import type { StoredDraft,TelegramCallback,TelegramMessage,TelegramUpdate } from './types';

const BOT_RATE_LIMIT=20;
export async function handleTelegramUpdate(update:TelegramUpdate){const db=createAdminClient();const from=update.message?.from??update.callback_query?.from;if(!from)return;
 const{error:seenError}=await db.from('telegram_updates').insert({telegram_update_id:update.update_id,telegram_user_id:from.id});if(seenError?.code==='23505')return;if(seenError)throw new Error('Unable to accept update');
 await Promise.all([db.from('telegram_updates').delete().eq('telegram_user_id',from.id).lt('created_at',new Date(Date.now()-86400000).toISOString()),db.from('telegram_drafts').update({status:'expired',raw_input:null}).eq('telegram_chat_id',update.message?.chat.id??update.callback_query?.message?.chat.id??0).eq('status','pending').lt('expires_at',new Date().toISOString())]);
 const since=new Date(Date.now()-60000).toISOString();const{count}=await db.from('telegram_updates').select('*',{count:'exact',head:true}).eq('telegram_user_id',from.id).gte('created_at',since);if((count??0)>BOT_RATE_LIMIT){if(update.message)await sendMessage(update.message.chat.id,'Please wait a moment before sending more entries.');return}
 if(update.callback_query)return handleCallback(update.callback_query);
 if(update.message?.text)return handleMessage(update.message);
}
async function connection(telegramUserId:number,chatId:number){const db=createAdminClient();const{data}=await db.from('telegram_connections').select('*').eq('telegram_user_id',telegramUserId).eq('telegram_chat_id',chatId).is('revoked_at',null).maybeSingle();return data}
async function handleMessage(message:TelegramMessage){const text=message.text!.trim();const from=message.from!;if(text.startsWith('/start')){const token=text.split(/\s+/)[1];if(!token){await sendMessage(message.chat.id,'Connect Telegram from your Finance account first.');return}const db=createAdminClient();const{data,error}=await db.rpc('consume_telegram_link_token',{p_token_hash:hashLinkToken(token),p_telegram_user_id:from.id,p_telegram_chat_id:message.chat.id,p_telegram_username:from.username??null});await sendMessage(message.chat.id,error||data!=='linked'?'This connection link is invalid, expired, or already used.':'Telegram is now connected to your Finance account.');return}
 if(text==='/help'){await sendMessage(message.chat.id,helpMessage);return}if(text==='/cancel'){const db=createAdminClient();await db.from('telegram_drafts').update({status:'cancelled',raw_input:null}).eq('telegram_chat_id',message.chat.id).eq('status','pending');await sendMessage(message.chat.id,'Cancelled.');return}
 const linked=await connection(from.id,message.chat.id);if(text==='/status'){await sendMessage(message.chat.id,linked?'Telegram is connected to your Finance account.':'Telegram is not connected. Connect it from Finance first.');return}if(!linked){await sendMessage(message.chat.id,'Connect Telegram from your Finance account first.',financeKeyboard());return}
 const db=createAdminClient();const[{data:accounts},{data:debts}]=await Promise.all([db.from('accounts').select('id,name,currency,is_default').eq('user_id',linked.user_id),db.from('debts').select('id,name,balance').eq('user_id',linked.user_id).gt('balance',0)]);const defaultAccount=accounts?.find(a=>a.is_default&&a.currency==='INR');const draft=parseQuickEntry(text,{debts:debts??[],defaultAccountId:defaultAccount?.id??null});
 if(draft.type==='unknown'||draft.confidence==='low'||!draft.amount){await sendMessage(message.chat.id,ambiguousMessage(draft.amount));return}if(!defaultAccount){await sendMessage(message.chat.id,'Choose a default INR account in Finance before using Quick Entry from Telegram.',financeKeyboard());return}if(draft.type==='debt_payment'&&!draft.debt_id){await sendMessage(message.chat.id,'I found more than one matching debt, or no exact match. Send the full debt name.');return}
 const expires=new Date(Date.now()+20*60000).toISOString();const{data:stored,error}=await db.from('telegram_drafts').insert({user_id:linked.user_id,telegram_chat_id:message.chat.id,raw_input:text,draft,status:'pending',expires_at:expires,telegram_update_id:message.message_id}).select('id').single();if(error)throw new Error('Unable to create draft');const debt=debts?.find(d=>d.id===draft.debt_id);await sendMessage(message.chat.id,draftMessage(draft,defaultAccount.name,debt?.name),draftKeyboard(stored.id,draft.type==='debt_payment'));
}
async function handleCallback(callback:TelegramCallback){if(!callback.data||!callback.message||!validDraftCallback(callback.data)){await answerCallback(callback.id,'Invalid action.');return}const[action,id]=callback.data.split(':');const db=createAdminClient();const linked=await connection(callback.from.id,callback.message.chat.id);if(!linked){await answerCallback(callback.id,'Connect Finance again.');return}const{data}=await db.from('telegram_drafts').select('*').eq('id',id).eq('user_id',linked.user_id).eq('telegram_chat_id',callback.message.chat.id).maybeSingle();const stored=data as StoredDraft|null;if(!stored||stored.status!=='pending'||new Date(stored.expires_at)<=new Date()){await answerCallback(callback.id,'This draft is no longer available.');return}
 if(action!=='qe_confirm'){await db.from('telegram_drafts').update({status:'cancelled',raw_input:null}).eq('id',id).eq('status','pending');await answerCallback(callback.id);await editMessage(callback.message.chat.id,callback.message.message_id,action==='qe_edit'?'Send the corrected transaction as a new message.':'Cancelled.');return}
 const{data:claimed}=await db.from('telegram_drafts').update({status:'processing'}).eq('id',id).eq('status','pending').select('*').maybeSingle();if(!claimed){await answerCallback(callback.id,'Already handled.');return}const draft=stored.draft;try{const{data:account}=await db.from('accounts').select('id,currency').eq('id',draft.account_id!).eq('user_id',linked.user_id).single();if(!account||account.currency!=='INR')throw new Error('Invalid account');let success='Entry added.';
  if(draft.type==='debt_payment'){const{data:result,error}=await db.rpc('record_telegram_debt_payment',{p_user_id:linked.user_id,p_debt_id:draft.debt_id,p_account_id:draft.account_id,p_amount:draft.amount,p_payment_date:draft.date,p_notes:'Telegram',p_idempotency_key:id});if(error)throw error;success=`${new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(draft.amount!)} paid toward debt.\n\nNew Freedom Number: ${new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(Number(result.freedom_number))}`}
  else{const{error}=await db.from('transactions').insert({user_id:linked.user_id,type:draft.type,amount:draft.amount,account_id:draft.account_id,category:draft.category,description:draft.description,transaction_date:draft.date,currency:'INR',source:'telegram',idempotency_key:id});if(error&&error.code!=='23505')throw error;success=`Added ${new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'}).format(draft.amount!)} to ${draft.category}.`}
  await db.from('telegram_drafts').update({status:'confirmed',confirmed_at:new Date().toISOString(),raw_input:null}).eq('id',id);await answerCallback(callback.id);await editMessage(callback.message.chat.id,callback.message.message_id,success);
 }catch{await db.from('telegram_drafts').update({status:'pending'}).eq('id',id).eq('status','processing');await answerCallback(callback.id,'Unable to save this entry.');}
}
