'use client';

import * as React from 'react';
import Link from 'next/link';
import {ArrowLeft,ExternalLink,MessageCircle} from 'lucide-react';
import {Button} from '@/components/ui/button';

type Connection={telegram_username:string|null;created_at:string};

export default function TelegramPage(){
  const[loading,setLoading]=React.useState(true),[connecting,setConnecting]=React.useState(false),[linkPending,setLinkPending]=React.useState(false),[connection,setConnection]=React.useState<Connection|null>(null),[error,setError]=React.useState(''),[confirm,setConfirm]=React.useState(false);
  const load=React.useCallback(async()=>{try{const response=await fetch('/api/telegram/connection',{cache:'no-store'});if(response.ok){const next=(await response.json()).connection;setConnection(next);if(next){setLinkPending(false);sessionStorage.removeItem('telegram-link-pending')}}}finally{setLoading(false)}},[]);
  React.useEffect(()=>{setLinkPending(sessionStorage.getItem('telegram-link-pending')==='1');load();const refresh=()=>{if(document.visibilityState==='visible')load()};window.addEventListener('focus',load);document.addEventListener('visibilitychange',refresh);return()=>{window.removeEventListener('focus',load);document.removeEventListener('visibilitychange',refresh)}},[load]);
  const connect=async()=>{setError('');setConnecting(true);const response=await fetch('/api/telegram/connection',{method:'POST'}),result=await response.json();if(!response.ok){setError(result?.error?.message??'Unable to connect Telegram.');setConnecting(false);return}sessionStorage.setItem('telegram-link-pending','1');window.location.assign(result.url)};
  const disconnect=async()=>{const response=await fetch('/api/telegram/connection',{method:'DELETE'});if(response.ok){setConnection(null);setConfirm(false)}else setError('Unable to disconnect Telegram.')};
  return <main className="mobile-page pt-2 sm:pt-3"><header className="flex items-start gap-3"><Link href="/more" aria-label="Back to More" className="tap-target mt-0.5 grid shrink-0 place-items-center rounded-full bg-secondary"><ArrowLeft className="h-5 w-5"/></Link><div className="min-w-0"><h1 className="text-3xl font-bold leading-tight tracking-tight">Telegram</h1><p className="mt-1 text-sm text-muted-foreground">Quick Entry from Telegram</p></div></header><section className="mobile-card p-5"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-primary/10 text-primary"><MessageCircle className="h-6 w-6"/></span>{loading?<p className="mt-4 text-muted-foreground">Checking connection…</p>:connection?<><h2 className="mt-4 text-xl font-semibold">Telegram connected</h2>{connection.telegram_username&&<p className="mt-1 text-muted-foreground">@{connection.telegram_username}</p>}<p className="mt-1 text-sm text-muted-foreground">Connected {new Date(connection.created_at).toLocaleDateString()}</p><Button variant="ghost" className="mt-3 w-full" onClick={load}>Refresh connection status</Button>{confirm?<div className="mt-3 rounded-2xl bg-destructive/10 p-4"><p className="text-sm">Disconnect Telegram? Existing transactions will stay in Finance.</p><div className="mt-3 flex gap-2"><Button variant="outline" className="flex-1" onClick={()=>setConfirm(false)}>Keep connected</Button><Button variant="destructive" className="flex-1" onClick={disconnect}>Disconnect</Button></div></div>:<Button variant="outline" className="mt-3 w-full" onClick={()=>setConfirm(true)}>Disconnect Telegram</Button>}</>:<><h2 className="mt-4 text-xl font-semibold">Send transactions directly from Telegram</h2><p className="mt-2 text-sm text-muted-foreground">Every entry is reviewed before it is saved.</p>{linkPending&&<p className="mt-3 rounded-xl bg-secondary p-3 text-sm">Finished in Telegram? Return here and refresh the connection status.</p>}<Button className="mt-5 min-h-12 w-full rounded-xl" onClick={connect} disabled={connecting}>{connecting?'Opening Telegram…':'Connect Telegram'}<ExternalLink className="ml-2 h-4 w-4"/></Button><Button variant="ghost" className="mt-2 w-full" onClick={load}>Refresh connection status</Button></>}{error&&<p role="alert" className="mt-3 text-sm text-destructive">{error}</p>}</section></main>;
}
