"use client";
import { useState } from "react";
import Link from "next/link";
import { ArrowRight, ShieldCheck, TrendingDown, WalletCards, Gauge, IndianRupee, Wallet } from "lucide-react";
import { useFinanceStore } from "@/lib/store";
import { calculateAvailableBalance, formatCurrency } from "@/lib/utils";
import { AddDebtDialog } from "@/components/add-debt-dialog";
import { AccountDialog } from "@/components/add-account-dialog";
import { RecordDebtPaymentDialog } from "@/components/record-debt-payment-dialog";

export default function OverviewPage(){
 const state=useFinanceStore(); const {debts,transactions,goals,accounts,expenses,incomes,projects,settings,demoMode,loadDemoData}=state;
 const[demoLoading,setDemoLoading]=useState(false),[demoError,setDemoError]=useState('');
 const now=new Date(),activeDebts=debts.filter(d=>d.balance>0),remaining=activeDebts.reduce((s,d)=>s+Number(d.balance),0),original=debts.reduce((s,d)=>s+Number(d.total),0),paid=Math.max(0,original-remaining),cleared=original?paid/original*100:0;
 const monthly=transactions.filter(t=>sameMonth(t.date,now)),previousDate=new Date(now.getFullYear(),now.getMonth()-1,1),previous=transactions.filter(t=>sameMonth(t.date,previousDate));
 const income=monthly.filter(t=>t.type==="income").reduce((s,t)=>s+Number(t.amount),0),living=monthly.filter(t=>t.type==="expense"&&t.category!=="Debt Payment").reduce((s,t)=>s+Number(t.amount),0),surplus=Math.max(0,income-living);
 const currentPayments=monthly.filter(t=>t.type==="expense"&&t.category==="Debt Payment").reduce((s,t)=>s+Number(t.amount),0),previousPayments=previous.filter(t=>t.type==="expense"&&t.category==="Debt Payment").reduce((s,t)=>s+Number(t.amount),0);
 const payoffMonths=surplus>0&&remaining>0?Math.ceil(remaining/surplus):0,nextDebt=[...activeDebts].sort((a,b)=>(b.rate||0)-(a.rate||0)||a.balance-b.balance)[0],otherMinimums=activeDebts.filter(d=>d.id!==nextDebt?.id).reduce((s,d)=>s+Number(d.minPayment||0),0),suggested=nextDebt?Math.min(nextDebt.balance,Math.max(nextDebt.minPayment||0,surplus-otherMinimums)):0;
 const emergency=goals.find(g=>g.name.toLowerCase().includes("emergency")); const canLoadDemo=!accounts.length&&!transactions.length&&!goals.length&&!expenses.length&&!debts.length&&!incomes.length&&!projects.length;
 const available=calculateAvailableBalance(accounts,transactions,settings);
 if(!debts.length&&!accounts.length&&!transactions.length)return <main className="mobile-page"><header><h1 className="text-3xl font-bold tracking-tight">Start your debt-free journey</h1><p className="mt-2 max-w-md text-muted-foreground">Add your debts and monthly finances to see your Freedom Number and payoff plan.</p></header><section className="mobile-card p-6"><span className="grid h-14 w-14 place-items-center rounded-2xl bg-primary/10 text-primary"><TrendingDown/></span><div className="mt-6 space-y-3"><AddDebtDialog><button className="tap-target w-full rounded-xl bg-primary px-5 font-semibold text-primary-foreground">Add your first debt</button></AddDebtDialog>{canLoadDemo&&<button disabled={demoLoading} onClick={async()=>{setDemoLoading(true);setDemoError('');if(!await loadDemoData())setDemoError('Sample data could not be added. Make sure your workspace is empty and try again.');setDemoLoading(false)}} className="tap-target w-full rounded-xl border border-border bg-card px-5 font-semibold disabled:opacity-60">{demoLoading?'Loading sample data…':'Try with sample data'}</button>}<AccountDialog><button className="tap-target w-full rounded-xl px-5 text-sm font-semibold text-muted-foreground hover:bg-secondary">I have no debt</button></AccountDialog>{demoError&&<p role="alert" className="text-sm text-destructive">{demoError}</p>}</div></section></main>;
 return <main className="mobile-page">
  <header><div className="flex items-center gap-2"><p className="text-sm text-muted-foreground">Your path to debt freedom</p>{demoMode&&<span className="rounded-full bg-primary/10 px-2 py-0.5 text-[11px] font-semibold text-primary">Sample data</span>}</div><h1 className="mt-1 text-3xl font-bold tracking-tight">Good {now.getHours()<12?"morning":now.getHours()<18?"afternoon":"evening"}, {settings.name||"there"}</h1></header>
  <section className="overflow-hidden rounded-2xl bg-primary p-5 text-primary-foreground shadow-lg"><p className="text-xs font-semibold uppercase tracking-widest opacity-75">The Freedom Number</p><p className="tabular mt-3 text-[clamp(2.35rem,12vw,4rem)] font-bold leading-none tracking-[-0.03em]">{formatCurrency(remaining,settings.currency)}</p><p className="mt-3 max-w-sm text-sm text-primary-foreground/80">Every rupee you clear moves you closer to financial freedom.</p><div className="mt-6 h-2 overflow-hidden rounded-full bg-black/15"><div className="h-full rounded-full bg-white" style={{width:`${Math.min(100,cleared)}%`}}/></div><div className="mt-3 flex justify-between text-xs"><span>{formatCurrency(paid,settings.currency)} paid</span><span>{cleared.toFixed(1)}% cleared</span></div></section>
  <section className="mobile-card grid grid-cols-2 divide-x divide-border p-4"><Metric label="Debt remaining" value={remaining}/><Metric label="Original debt" value={original}/></section>
  <section className="mobile-card p-5"><div className="flex items-start gap-3"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-emerald-500/10 text-primary"><Wallet className="h-5 w-5"/></span><div className="min-w-0 flex-1"><h2 className="font-semibold">Available Balance</h2><p className="tabular mt-1 text-3xl font-bold">{formatCurrency(available.balance,settings.currency)}</p><p className="text-sm text-muted-foreground">{available.accountCount?`Across ${available.accountCount} ${available.accountCount===1?'account':'accounts'}`:'Add an account to see what you have available.'}</p></div></div>{available.accountCount===0&&<AccountDialog><button type="button" className="tap-target mt-4 w-full rounded-xl bg-secondary px-4 font-semibold">Add Account</button></AccountDialog>}</section>
  <section className="mobile-card p-5"><div className="flex items-start gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-primary/10 text-primary"><Gauge className="h-5 w-5"/></span><div className="min-w-0 flex-1"><h2 className="font-semibold">Monthly payoff power</h2><p className="tabular mt-1 text-3xl font-bold">{formatCurrency(surplus,settings.currency)}</p><p className="text-sm text-muted-foreground">Income minus living expenses</p></div></div><div className="mt-5 rounded-xl bg-secondary p-4"><p className="text-xs font-semibold text-muted-foreground">Estimated time to debt freedom</p><p className="mt-1 font-semibold">{payoffMonths?formatDuration(payoffMonths):"Add income and monthly expenses to calculate your debt-free timeline."}</p>{payoffMonths>0&&<p className="mt-1 text-xs text-muted-foreground">Simple principal estimate before interest.</p>}</div></section>
  {nextDebt&&<section className="rounded-2xl border border-primary/30 bg-primary/5 p-5"><p className="text-xs font-semibold uppercase tracking-wider text-primary">Next debt to attack</p><div className="mt-3 flex items-start justify-between gap-3"><div><h2 className="text-xl font-bold">{nextDebt.name}</h2><p className="text-sm text-muted-foreground">{formatCurrency(nextDebt.balance,settings.currency)} remaining · {nextDebt.rate?`${nextDebt.rate}% APR`:"APR not provided"}</p></div><span className="rounded-full bg-primary px-2.5 py-1 text-xs font-semibold text-primary-foreground">Suggested focus</span></div><p className="mt-4 text-sm">Suggested this month: <strong>{formatCurrency(suggested,settings.currency)}</strong></p><RecordDebtPaymentDialog initialDebtId={nextDebt.id}><button className="tap-target mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-primary px-4 font-semibold text-primary-foreground">Record payment<ArrowRight className="h-4 w-4"/></button></RecordDebtPaymentDialog></section>}
  <section><SectionTitle title="Debt portfolio" href="/debts"/><div className="mobile-card divide-y divide-border overflow-hidden">{activeDebts.map((debt,index)=>{const progress=debt.total?Math.max(0,(debt.total-debt.balance)/debt.total*100):0;return <Link href={`/debts/${debt.id}`} key={debt.id} className="block p-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-secondary text-primary"><IndianRupee className="h-4 w-4"/></span><div className="min-w-0 flex-1"><p className="truncate font-semibold">{debt.name}</p><p className="text-xs text-muted-foreground">{debt.rate?`${debt.rate}% APR`:"APR not provided"}</p></div><div className="text-right"><p className="tabular text-sm font-semibold">{formatCurrency(debt.balance,settings.currency)}</p>{index===0&&debt.id===nextDebt?.id&&<p className="text-[10px] font-semibold text-primary">Priority</p>}</div></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary" style={{width:`${Math.min(100,progress)}%`}}/></div></Link>})}</div></section>
  <section><h2 className="mb-3 text-xl font-semibold">This month</h2><div className="mobile-card grid grid-cols-3 divide-x divide-border p-4"><Metric label="Income" value={income}/><Metric label="Expenses" value={living}/><Metric label="For debt" value={surplus}/></div></section>
  <section className="mobile-card p-5"><div className="flex items-center gap-2"><WalletCards className="h-5 w-5 text-primary"/><h2 className="font-semibold">Payoff momentum</h2></div>{currentPayments||previousPayments?<><p className="tabular mt-4 text-2xl font-bold">{formatCurrency(currentPayments,settings.currency)} <span className="text-sm font-normal text-muted-foreground">paid this month</span></p><p className="mt-1 text-sm text-muted-foreground">{currentPayments>=previousPayments?"Up":"Down"} {formatCurrency(Math.abs(currentPayments-previousPayments),settings.currency)} from last month.</p></>:<p className="mt-3 text-sm text-muted-foreground">Record debt payments to see your monthly momentum.</p>}</section>
  {emergency&&<section><h2 className="mb-3 text-xl font-semibold">Financial safety</h2><Link href="/goals" className="mobile-card block p-5"><div className="flex items-center gap-3"><ShieldCheck className="h-6 w-6 text-primary"/><div className="flex-1"><p className="font-semibold">Emergency Fund</p><p className="text-sm text-muted-foreground">A buffer while you pay down debt</p></div><p className="tabular text-sm font-semibold">{Math.round(emergency.saved/emergency.target*100)}%</p></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary" style={{width:`${Math.min(100,emergency.saved/emergency.target*100)}%`}}/></div><p className="mt-2 text-xs text-muted-foreground">{formatCurrency(emergency.saved,settings.currency)} of {formatCurrency(emergency.target,settings.currency)}</p></Link></section>}
 </main>;
 function Metric({label,value}:{label:string;value:number}){return <div className="min-w-0 px-2 first:pl-0 last:pr-0"><p className="text-[11px] text-muted-foreground">{label}</p><p className="tabular mt-1 truncate text-sm font-semibold sm:text-base">{formatCurrency(value,settings.currency)}</p></div>}
}
function sameMonth(value:string,date:Date){const item=new Date(value);return item.getMonth()===date.getMonth()&&item.getFullYear()===date.getFullYear()}
function formatDuration(months:number){const years=Math.floor(months/12),rest=months%12;if(!years)return `${months} ${months===1?"month":"months"}`;return `${years} ${years===1?"year":"years"}${rest?` ${rest} ${rest===1?"month":"months"}`:""}`}
function SectionTitle({title,href}:{title:string;href:string}){return <div className="mb-3 flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><Link href={href} className="tap-target flex items-center text-sm font-semibold text-primary">View all<ArrowRight className="ml-1 h-4 w-4"/></Link></div>}
