"use client";
import Link from "next/link";
import { useFinanceStore } from "@/lib/store";
import { formatCurrency, getAccountBalance } from "@/lib/utils";
import { ArrowDownLeft, ArrowUpRight, ArrowRightLeft, Wallet, Target, Lightbulb, ChevronRight } from "lucide-react";
import { AddTransactionDialog } from "@/components/add-transaction-dialog";
import { AccountDialog } from "@/components/add-account-dialog";

export default function OverviewPage(){
 const {accounts,transactions,goals,expenses,settings}=useFinanceStore();
 const now=new Date(); const month=now.getMonth(); const year=now.getFullYear();
 const monthly=transactions.filter(t=>{const d=new Date(t.date);return d.getMonth()===month&&d.getFullYear()===year});
 const income=monthly.filter(t=>t.type==="income").reduce((s,t)=>s+Number(t.amount),0);
 const spent=monthly.filter(t=>t.type==="expense").reduce((s,t)=>s+Number(t.amount),0);
 const saved=income-spent; const budget=expenses.reduce((s,e)=>s+Number(e.budgeted),0);
 const balances=accounts.map(a=>({...a,balance:getAccountBalance(a.id,accounts,transactions,settings)}));
 const total=balances.reduce((s,a)=>s+a.balance,0); const budgetPct=budget?Math.min(100,Math.round(spent/budget*100)):0;
 if(!accounts.length&&!transactions.length) return <main className="mobile-page"><header><p className="text-sm text-muted-foreground">{now.toLocaleDateString(undefined,{weekday:"long",month:"short",day:"numeric"})}</p><h1 className="text-3xl font-bold tracking-tight">Welcome to Finance</h1></header><section className="mobile-card p-6 text-center"><span className="mx-auto mb-4 grid h-14 w-14 place-items-center rounded-2xl bg-emerald-400/20 text-primary"><Wallet/></span><h2 className="text-xl font-semibold">Let’s build your financial picture.</h2><p className="mx-auto mt-2 max-w-sm text-sm text-muted-foreground">Start with the account you use most. Your dashboard will grow with every entry.</p><AccountDialog><button className="mt-5 min-h-12 rounded-xl bg-primary px-5 font-semibold text-primary-foreground">Add your first account</button></AccountDialog></section></main>;
 return <main className="mobile-page">
  <header><p className="text-sm text-muted-foreground">{now.toLocaleDateString(undefined,{weekday:"long",month:"short",day:"numeric"})}</p><h1 className="text-3xl font-bold tracking-tight">Good {now.getHours()<12?"morning":now.getHours()<18?"afternoon":"evening"}, {settings.name||"there"}</h1></header>
  <section className="overflow-hidden rounded-2xl bg-primary p-5 text-primary-foreground shadow-lg"><p className="text-xs font-semibold uppercase tracking-widest opacity-70">Total balance</p><p className="tabular mt-3 text-4xl font-bold tracking-tight">{formatCurrency(total,settings.currency)}</p><div className="mt-5 grid grid-cols-3 rounded-xl bg-white/10 p-3 text-sm"><Metric label="Income" value={income} positive/><Metric label="Spent" value={spent}/><Metric label="Saved" value={saved} positive={saved>=0}/></div></section>
  <div className="grid grid-cols-3 gap-2"><AddTransactionDialog initialType="expense"><Quick label="Expense" icon={ArrowUpRight}/></AddTransactionDialog><AddTransactionDialog initialType="income"><Quick label="Income" icon={ArrowDownLeft} positive/></AddTransactionDialog><AddTransactionDialog initialType="transfer"><Quick label="Transfer" icon={ArrowRightLeft}/></AddTransactionDialog></div>
  <section className="mobile-card p-4"><div className="flex items-center justify-between"><div><h2 className="text-lg font-semibold">Monthly spending</h2><p className="text-sm text-muted-foreground">{formatCurrency(spent,settings.currency)} of {formatCurrency(budget,settings.currency)} budget</p></div><span className="text-sm font-semibold text-primary">{budgetPct}%</span></div><div className="mt-4 h-2 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-primary" style={{width:`${budgetPct}%`}}/></div></section>
  <section><SectionTitle title="Accounts" href="/accounts"/>
   <div className="grid grid-cols-2 gap-3">{balances.slice(0,4).map(a=><Link href={`/accounts/${a.id}`} key={a.id} className="mobile-card min-w-0 p-4"><span className="mb-5 grid h-9 w-9 place-items-center rounded-xl bg-secondary text-primary"><Wallet className="h-5 w-5"/></span><p className="truncate text-sm text-muted-foreground">{a.name}</p><p className="tabular truncate text-xl font-semibold">{formatCurrency(a.balance,a.currency)}</p></Link>)}</div>
  </section>
  <section><SectionTitle title="Financial goals" href="/goals"/><div className="space-y-3">{goals.slice(0,2).map(g=>{const p=g.target?Math.min(100,Math.round(g.saved/g.target*100)):g.manualProgress||0;return <Link href="/goals" key={g.id} className="mobile-card block p-4"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-400/15 text-primary"><Target className="h-5 w-5"/></span><div className="min-w-0 flex-1"><p className="truncate font-semibold">{g.name}</p><p className="text-sm text-muted-foreground">{formatCurrency(g.saved,settings.currency)} saved</p></div><span className="text-sm font-semibold text-primary">{p}%</span></div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-secondary"><div className="h-full rounded-full bg-emerald-400" style={{width:`${p}%`}}/></div></Link>})}</div></section>
  <section><SectionTitle title="Recent activity" href="/transactions"/><div className="mobile-card divide-y divide-border overflow-hidden">{transactions.slice(0,4).map(t=><div key={t.id} className="flex min-h-[64px] items-center gap-3 px-4"><span className="grid h-10 w-10 place-items-center rounded-xl bg-secondary">{t.type==="income"?<ArrowDownLeft className="h-5 w-5 text-emerald-500"/>:<ArrowUpRight className="h-5 w-5"/>}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{t.description||t.category}</p><p className="truncate text-xs text-muted-foreground">{t.category}</p></div><p className={t.type==="income"?"tabular text-sm font-semibold text-emerald-600":"tabular text-sm font-semibold"}>{t.type==="income"?"+":"-"}{formatCurrency(t.amount,t.currency)}</p></div>)}</div></section>
  <div className="flex gap-3 rounded-2xl bg-emerald-400/10 p-4 text-sm"><Lightbulb className="h-5 w-5 shrink-0 text-primary"/><p>{saved>=0?"You’re spending within this month’s income. Keep the buffer working for you.":"Spending is above income this month. Review recent activity to spot what changed."}</p></div>
 </main>;
 function Metric({label,value,positive}:{label:string;value:number;positive?:boolean}){return <div><p className="text-xs opacity-70">{label}</p><p className={positive?"tabular font-semibold text-emerald-200":"tabular font-semibold"}>{formatCurrency(value,settings.currency)}</p></div>}
}
function Quick({label,icon:Icon,positive}:{label:string;icon:typeof Wallet;positive?:boolean}){return <button className="tap-target flex w-full items-center justify-center gap-1.5 rounded-xl border border-border bg-card px-2 py-3 text-sm font-semibold"><Icon className={positive?"h-4 w-4 text-emerald-500":"h-4 w-4"}/>{label}</button>}
function SectionTitle({title,href}:{title:string;href:string}){return <div className="mb-3 flex items-center justify-between"><h2 className="text-xl font-semibold">{title}</h2><Link href={href} className="flex min-h-11 items-center gap-1 text-sm font-semibold text-primary">View all<ChevronRight className="h-4 w-4"/></Link></div>}
