import type { Metadata } from "next";
import { ContactCopy, LegalPage, type LegalSection } from "@/components/legal-page";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How ZeroDebt collects, uses, stores, and protects personal and financial information.",
  alternates: { canonical: "/privacy" },
};

const sections: LegalSection[] = [
  { id: "information", title: "Information we collect", content: <><p>We collect information you choose to provide when using ZeroDebt. This may include your name and profile details, email address or account identity, debt balances and terms, income, expenses, account balances, goals, budgets, and transaction records.</p><p>We also receive limited technical information needed to operate and protect the service, such as authentication events, session information, device or browser information, and diagnostic data.</p></> },
  { id: "use", title: "How we use information", content: <><p>We use your information to provide the features you request, including your Freedom Number, payoff calculations, debt strategy, budget tracking, goals, transaction history, account balances, and financial progress.</p><p>We may also use limited technical information to maintain sessions, prevent abuse, diagnose failures, improve reliability, and communicate important service or security information.</p></> },
  { id: "authentication", title: "Authentication", content: <p>ZeroDebt uses Supabase Auth to manage accounts and sessions. You may sign in using Google Sign-In or email authentication. Google and Supabase process the information required to authenticate you under their own terms and privacy policies. ZeroDebt does not receive your Google password.</p> },
  { id: "telegram", title: "Telegram integration", content: <><p>If you connect Telegram, ZeroDebt stores the minimum identifiers needed to associate your Telegram account or chat with your ZeroDebt account. Quick Entry messages are used to create a transaction draft for your review. A transaction is added to your financial records only after the applicable confirmation flow.</p><p>We avoid retaining Telegram message content when it is no longer needed for the requested workflow, subject to operational logs, abuse prevention, and records you choose to confirm.</p></> },
  { id: "ai", title: "Ask ZeroDebt and AI", content: <><p>When Ask ZeroDebt is enabled and you use it, relevant portions of your financial information and your question may be sent to the configured AI provider to prepare an answer. We aim to minimize the information sent and exclude unrelated identifiers where practical.</p><p>AI features provide explanations and planning support. They do not make autonomous financial decisions and do not silently create, edit, or delete your financial records.</p></> },
  { id: "providers", title: "Service providers and storage", content: <><p>ZeroDebt relies on service providers to operate the product. These currently include Supabase for database and authentication services, Vercel for application hosting, Google for Google Sign-In, Telegram for connected bot interactions, and an AI provider where Ask ZeroDebt is enabled.</p><p>These providers may process data in locations outside your country. Their handling of data is also governed by their respective terms and privacy notices.</p></> },
  { id: "sessions", title: "Cookies and session storage", content: <p>We use cookies and similar browser storage that are necessary to authenticate you, keep you signed in, protect account access, remember essential preferences, and operate the application. ZeroDebt does not require advertising cookies for its core finance features.</p> },
  { id: "security", title: "Data security", content: <p>We use technical and organizational measures intended to protect personal and financial information against unauthorized access, loss, misuse, or alteration. No online service can guarantee absolute security, and users should protect their devices and account access.</p> },
  { id: "retention", title: "Data retention", content: <p>We retain account and financial information while your account is active and as needed to provide the service, resolve disputes, prevent abuse, meet legitimate operational needs, or comply with applicable legal obligations. Retention periods may differ by data type and purpose.</p> },
  { id: "rights", title: "Your choices and rights", content: <><p>Depending on your location and the capabilities available in the product, you may request access to, correction of, export of, or deletion of your personal information. You may also request account closure.</p><p>Some records may need to be retained where required by law or for legitimate security, fraud-prevention, or dispute-resolution purposes. We will explain any applicable limitation when responding to a request.</p></> },
  { id: "deletion", title: "Deleting data or your account", content: <p>You can delete supported financial records through ZeroDebt. If complete self-service account deletion is not available, contact support to request account closure and deletion. Account deletion may permanently remove financial history, calculations, linked integrations, and conversation history and may not be reversible.</p> },
  { id: "children", title: "Children", content: <p>ZeroDebt is not intended for children under 13, or under any higher minimum age required to use an online service in their location. We do not knowingly collect personal information from children who are not eligible to use the service.</p> },
  { id: "international", title: "International users", content: <p>ZeroDebt may be used from different countries. By using the service, you understand that information may be processed in countries where ZeroDebt or its service providers operate, subject to applicable law and appropriate safeguards where required.</p> },
  { id: "sale", title: "No sale of personal data", content: <p>ZeroDebt does not sell personal data. If our practices materially change, we will update this policy and provide any choices required by applicable law.</p> },
  { id: "changes", title: "Changes to this policy", content: <p>We may update this Privacy Policy as ZeroDebt evolves or legal requirements change. We will revise the “Last updated” date and provide additional notice when a change is material and such notice is appropriate.</p> },
  { id: "contact", title: "Contact", content: <ContactCopy /> },
];

export default function PrivacyPage() {
  return <LegalPage title="Privacy Policy" summary="This policy explains what ZeroDebt collects, why it is used, and the choices available to you." updated="September 7, 2026" sections={sections} />;
}
