"use client";
import * as React from "react";
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogTrigger} from "@/components/ui/dialog";
import {Input} from "@/components/ui/input";
import {useFinanceStore,type Income} from "@/lib/store";

export function OnboardingIncomeDialog({children,onSaved}:{children:React.ReactNode;onSaved?:()=>void}){
 const[open,setOpen]=React.useState(false),[source,setSource]=React.useState("Salary"),[name,setName]=React.useState(""),[amount,setAmount]=React.useState(""),[saving,setSaving]=React.useState(false),[error,setError]=React.useState("");const currency=useFinanceStore(s=>s.settings.currency);
 async function submit(e:React.FormEvent){e.preventDefault();const value=Number(amount);if(!Number.isFinite(value)||value<=0){setError("Enter a monthly income greater than zero.");return}setSaving(true);setError("");try{const input={name:name.trim()||source,type:source==="Business"||source==="Freelance"?source:"placeholder",status:"active",currency,expectedMonthly:value,actualThisMonth:0,notes:"",color:"#166534",icon:"briefcase",linkedAccountId:""};const response=await fetch("/api/incomes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(input)});if(!response.ok)throw new Error();const row=await response.json();const income:Income={...input,id:row.id,type:input.type as Income["type"],status:"active",currency:row.currency??currency,expectedMonthly:Number(row.expected_monthly??value),actualThisMonth:Number(row.actual_this_month??0),linkedAccountId:row.linked_account_id??""};useFinanceStore.setState(s=>({incomes:[...s.incomes,income]}));setOpen(false);setName("");setAmount("");onSaved?.()}catch{setError("We could not save your income. Check your connection and try again.")}finally{setSaving(false)}}
 return <Dialog open={open} onOpenChange={v=>{if(!saving)setOpen(v)}}><DialogTrigger asChild>{children}</DialogTrigger><DialogContent className="bottom-sheet max-h-[90dvh] overflow-y-auto sm:max-w-[425px]"><DialogHeader><DialogTitle>Add monthly income</DialogTitle></DialogHeader><form onSubmit={submit} className="space-y-5 pt-3"><fieldset><legend className="mb-2 text-sm font-semibold">Income source</legend><div className="grid grid-cols-2 gap-2">{["Salary","Business","Freelance","Other"].map(v=><button key={v} type="button" aria-pressed={source===v} onClick={()=>setSource(v)} className={`tap-target rounded-xl border px-3 text-sm font-semibold ${source===v?"border-primary bg-primary/10 text-primary":"border-border bg-card"}`}>{v}</button>)}</div></fieldset><div><label htmlFor="onboarding-income-amount" className="mb-2 block text-sm font-semibold">Monthly amount</label><Input id="onboarding-income-amount" inputMode="decimal" type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)} className="text-base" placeholder="0" required/></div><div><label htmlFor="onboarding-income-name" className="mb-2 block text-sm font-semibold">Name <span className="font-normal text-muted-foreground">(optional)</span></label><Input id="onboarding-income-name" value={name} onChange={e=>setName(e.target.value)} className="text-base" placeholder={source}/></div>{error&&<p role="alert" className="rounded-xl bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<button type="submit" disabled={saving} className="tap-target w-full rounded-xl bg-primary px-5 font-semibold text-primary-foreground disabled:opacity-60">{saving?"Saving income…":"Save income"}</button></form></DialogContent></Dialog>
}
