"use client";
import * as React from 'react';
import { ArrowLeft, Sparkles } from 'lucide-react';
import { useFinanceStore, type Transaction } from '@/lib/store';
import { parseQuickEntry, type QuickEntryDraft, type QuickEntryType } from '@/lib/quick-entry/parser';
import { EXPENSE_CATEGORIES, INCOME_CATEGORIES } from '@/lib/quick-entry/rules';
import { formatCurrency } from '@/lib/utils';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { getBaseCurrency, resolveQuickEntryAccount } from '@/lib/currency';

type Step = 'input' | 'review' | 'success';
export function QuickEntryDialog({open,onOpenChange}:{open:boolean;onOpenChange:(open:boolean)=>void}) {
  const {accounts,debts,settings,recordDebtPayment}=useFinanceStore();
  const [step,setStep]=React.useState<Step>('input'),[raw,setRaw]=React.useState(''),[draft,setDraft]=React.useState<QuickEntryDraft|null>(null);
  const [pending,setPending]=React.useState(false),[error,setError]=React.useState(''),[message,setMessage]=React.useState('');
  const inputRef=React.useRef<HTMLInputElement>(null);
  const baseCurrency=getBaseCurrency({base_currency:settings.currency});
  const paymentAccounts=accounts.filter(account=>account.type!=='credit'&&account.type!=='receivable'&&account.currency===baseCurrency);
  const accountResolution=baseCurrency?resolveQuickEntryAccount(accounts,baseCurrency):null;
  React.useEffect(()=>{if(open){setStep('input');setRaw('');setDraft(null);setError('');setMessage('');setTimeout(()=>inputRef.current?.focus(),100)}},[open]);
  const parse=()=>{if(!baseCurrency){setError('Set your base currency in Settings before using Quick Entry.');return}if(accountResolution?.status==='none'){setError('Add your first account or load sample data before using Quick Entry.');return}const next=parseQuickEntry(raw,{debts,baseCurrency,defaultAccountId:accountResolution?.account?.id??null});setDraft(next);setStep('review');setError('')};
  const update=(change:Partial<QuickEntryDraft>)=>setDraft(current=>current?{...current,...change}:current);
  const canConfirm=Boolean(draft?.amount&&draft.type!=='unknown'&&draft.account_id&&draft.category&&(draft.type!=='debt_payment'||draft.debt_id));
  const confirm=async()=>{if(!draft||!canConfirm||pending)return;setPending(true);setError('');try{
    if(draft.type==='debt_payment'){await recordDebtPayment(draft.debt_id!,draft.account_id!,draft.amount!,draft.date,'Quick Entry');const debt=debts.find(item=>item.id===draft.debt_id);const freedom=useFinanceStore.getState().debts.reduce((sum,item)=>sum+item.balance,0);setMessage(`${formatCurrency(draft.amount!,settings.currency)} paid toward ${debt?.name??'debt'}. New Freedom Number: ${formatCurrency(freedom,settings.currency)}.`)}
    else {const idempotencyKey=crypto.randomUUID();const response=await fetch('/api/transactions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type:draft.type,amount:draft.amount,accountId:draft.account_id,category:draft.category,description:draft.description,date:draft.date,currency:draft.currency,source:'quick_entry',idempotencyKey})});const result=await response.json();if(!response.ok)throw new Error(result?.error?.message??'The transaction could not be added.');const transaction:Transaction={id:result.id,type:result.type,amount:Number(result.amount),accountId:result.account_id,toAccountId:result.to_account_id??undefined,category:result.category,description:result.description,date:result.transaction_date,currency:result.currency,createdAt:result.created_at,notes:result.notes??''};useFinanceStore.setState(state=>({transactions:[transaction,...state.transactions]}));setMessage(`Added ${formatCurrency(transaction.amount,settings.currency)} to ${transaction.category}.`)}
    setStep('success');
  }catch(reason){setError(reason instanceof Error?reason.message:'The entry could not be saved.')}finally{setPending(false)}};
  const categories=draft?.type==='income'?INCOME_CATEGORIES:EXPENSE_CATEGORIES;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="finance-sheet max-h-[92dvh] overflow-y-auto border-border bg-card sm:max-w-[460px] sm:rounded-2xl max-sm:top-auto max-sm:bottom-0 max-sm:translate-y-0 max-sm:rounded-b-none max-sm:rounded-t-3xl max-sm:pb-[calc(1.25rem+env(safe-area-inset-bottom))] [&_textarea]:text-base">
    {step==='input'&&<><DialogHeader><DialogTitle className="text-xl">Quick Entry</DialogTitle><DialogDescription>Type a transaction in your own words.</DialogDescription></DialogHeader><form onSubmit={event=>{event.preventDefault();if(raw.trim())parse()}} className="space-y-5 py-3"><div className="space-y-2"><label htmlFor="quick-entry" className="text-sm font-semibold">What happened?</label><Input ref={inputRef} id="quick-entry" autoComplete="off" enterKeyHint="go" value={raw} onChange={event=>setRaw(event.target.value)} placeholder="biryani 500" className="min-h-14 rounded-xl bg-secondary/50 text-base"/></div><div className="rounded-2xl bg-secondary/60 p-4 text-sm text-muted-foreground"><p className="mb-2 font-medium text-foreground">Try something like</p><p>“fuel 1200” · “salary 120000”</p><p>“paid 10000 credit card”</p></div>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}<Button className="min-h-12 w-full rounded-xl" disabled={!raw.trim()}>Continue</Button></form></>}
    {step==='review'&&draft&&<><DialogHeader><button onClick={()=>setStep('input')} className="mb-2 flex w-fit items-center gap-1 text-sm text-muted-foreground"><ArrowLeft className="h-4 w-4"/>Edit text</button><DialogTitle>Review entry</DialogTitle><DialogDescription>Nothing is saved until you confirm.</DialogDescription></DialogHeader><div className="space-y-4 py-2"><div className="rounded-2xl bg-primary/10 p-5 text-center"><p className="text-xs font-bold uppercase tracking-wider text-primary">{draft.type.replace('_',' ')}</p><p className="mt-1 text-3xl font-bold">{draft.amount?formatCurrency(draft.amount,draft.currency):'Amount needed'}</p><p className="mt-1 text-sm text-muted-foreground">{draft.description}</p></div>{draft.confidence==='low'&&<p className="rounded-xl bg-amber-500/10 p-3 text-sm text-amber-700 dark:text-amber-300">I found part of this entry, but need a little more information.</p>}
      <Field label="Type"><Select value={draft.type} onValueChange={value=>update({type:value as QuickEntryType,category:value==='debt_payment'?'Debt Payment':null,debt_id:value==='debt_payment'?draft.debt_id:null})}><SelectTrigger className="min-h-12 rounded-xl"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="expense">Expense</SelectItem><SelectItem value="income">Income</SelectItem><SelectItem value="debt_payment">Debt Payment</SelectItem></SelectContent></Select></Field>
      <Field label="Amount"><Input type="number" inputMode="decimal" min="0.01" step="0.01" value={draft.amount??''} onChange={e=>update({amount:Number(e.target.value)||null})} className="min-h-12 rounded-xl"/></Field>
      <Field label="Description"><Input value={draft.description} maxLength={200} onChange={e=>update({description:e.target.value})} className="min-h-12 rounded-xl"/></Field>
      {draft.type==='debt_payment'?<Field label="Debt"><Select value={draft.debt_id??''} onValueChange={debt_id=>update({debt_id,category:'Debt Payment'})}><SelectTrigger className="min-h-12 rounded-xl"><SelectValue placeholder="Select debt"/></SelectTrigger><SelectContent>{debts.filter(d=>d.balance>0).map(d=><SelectItem key={d.id} value={d.id}>{d.name}</SelectItem>)}</SelectContent></Select></Field>:<Field label="Category"><Select value={draft.category??''} onValueChange={category=>update({category})}><SelectTrigger className="min-h-12 rounded-xl"><SelectValue placeholder="Select category"/></SelectTrigger><SelectContent>{categories.map(category=><SelectItem key={category} value={category}>{category}</SelectItem>)}</SelectContent></Select></Field>}
      <Field label={draft.type==='debt_payment'?'Pay from account':'Account'}><Select value={draft.account_id??''} onValueChange={account_id=>update({account_id})}><SelectTrigger className="min-h-12 rounded-xl"><SelectValue placeholder="Select account"/></SelectTrigger><SelectContent>{paymentAccounts.map(account=><SelectItem key={account.id} value={account.id}>{account.name}</SelectItem>)}</SelectContent></Select></Field>
      <Field label="Date"><Input type="date" value={draft.date} onChange={e=>update({date:e.target.value})} className="min-h-12 rounded-xl"/></Field>{error&&<p role="alert" className="text-sm text-destructive">{error}</p>}
    </div><DialogFooter className="sticky bottom-0 bg-card pt-2"><Button onClick={confirm} disabled={!canConfirm||pending} className="min-h-12 w-full rounded-xl">{pending?'Saving…':draft.type==='debt_payment'?'Confirm Payment':'Confirm'}</Button></DialogFooter></>}
    {step==='success'&&<div className="py-8 text-center"><span className="mx-auto grid h-12 w-12 place-items-center rounded-full bg-primary/15 text-primary"><Sparkles className="h-6 w-6"/></span><DialogTitle className="mt-4">Entry added</DialogTitle><p role="status" className="mt-2 text-sm text-muted-foreground">{message}</p><Button onClick={()=>onOpenChange(false)} className="mt-6 min-h-12 w-full rounded-xl">Done</Button></div>}
  </DialogContent></Dialog>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-2"><p className="text-xs font-semibold text-muted-foreground">{label}</p>{children}</div>}
