"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
import { Home, ReceiptText, PieChart, MoreHorizontal, Plus, Wallet, ArrowLeftRight, TrendingDown, TrendingUp, Kanban, Target, Settings, X } from "lucide-react";
import { cn } from "@/lib/utils";
import { AddTransactionDialog } from "@/components/add-transaction-dialog";
import { AccountDialog } from "@/components/add-account-dialog";
import { AddDebtDialog } from "@/components/add-debt-dialog";
import { AddGoalDialog } from "@/components/add-goal-dialog";

const desktopItems = [["Overview","/overview",Home],["Accounts","/accounts",Wallet],["Ledger","/transactions",ArrowLeftRight],["Debts","/debts",TrendingDown],["Income","/income",TrendingUp],["Pipeline","/pipeline",Kanban],["Budget","/budget",PieChart],["Goals","/goals",Target]] as const;
const mobileItems = [["Home","/overview",Home],["Activity","/transactions",ReceiptText],["Plan","/plan",PieChart],["More","/more",MoreHorizontal]] as const;
function FinanceMark(){return <span className="grid h-9 w-9 place-items-center rounded-xl bg-primary text-primary-foreground"><TrendingUp className="h-5 w-5"/></span>}

export function SidebarNav(){
 const pathname=usePathname(); const [sheetOpen,setSheetOpen]=useState(false);
 return <>
  <header className="safe-top fixed inset-x-0 top-0 z-40 border-b border-border bg-background/90 backdrop-blur-xl lg:hidden"><div className="flex h-16 items-center justify-between px-4"><Link href="/overview" className="flex items-center gap-2"><FinanceMark/><span className="text-lg font-semibold">Finance</span></Link><Link href="/settings" aria-label="Open settings" className="tap-target grid place-items-center rounded-full bg-secondary"><Settings className="h-5 w-5"/></Link></div></header>
  <aside className="hidden lg:flex h-screen w-64 sticky top-0 flex-col border-r border-border bg-card"><Link href="/overview" className="flex items-center gap-3 p-6"><FinanceMark/><span className="text-xl font-bold">Finance</span></Link><nav className="flex-1 space-y-1 overflow-y-auto px-4">{desktopItems.map(([name,href,Icon])=><Link key={href} href={href} className={cn("flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium",pathname===href?"bg-primary text-primary-foreground":"text-muted-foreground hover:bg-secondary hover:text-foreground")}><Icon className="h-4 w-4"/>{name}</Link>)}</nav><Link href="/settings" className="m-4 flex items-center gap-3 rounded-xl px-3 py-2.5 text-sm text-muted-foreground hover:bg-secondary"><Settings className="h-4 w-4"/>Settings</Link></aside>
  <nav className="safe-bottom fixed inset-x-0 bottom-0 z-50 border-t border-border bg-card/95 backdrop-blur-xl lg:hidden"><div className="grid h-16 grid-cols-5 items-center px-2">{mobileItems.slice(0,2).map(([name,href,Icon])=><MobileLink key={href} name={name} href={href} icon={Icon} active={pathname===href}/>)}<button aria-label="Add financial item" onClick={()=>setSheetOpen(true)} className="tap-target mx-auto -mt-5 grid h-14 w-14 place-items-center rounded-full bg-primary text-primary-foreground shadow-lg active:scale-95"><Plus className="h-7 w-7"/></button>{mobileItems.slice(2).map(([name,href,Icon])=><MobileLink key={href} name={name} href={href} icon={Icon} active={pathname===href||(href==="/plan"&&["/budget","/goals","/debts"].includes(pathname))}/>)}</div></nav>
  {sheetOpen&&<div className="fixed inset-0 z-[60] bg-slate-950/55 backdrop-blur-sm lg:hidden" onClick={()=>setSheetOpen(false)}><section role="dialog" aria-modal="true" aria-label="Add financial item" className="safe-bottom absolute inset-x-0 bottom-0 rounded-t-3xl bg-card p-5 shadow-2xl" onClick={e=>e.stopPropagation()}><div className="mx-auto mb-4 h-1 w-10 rounded-full bg-muted-foreground/30"/><div className="mb-5 flex items-center justify-between"><h2 className="text-xl font-semibold">What would you like to add?</h2><button aria-label="Close" onClick={()=>setSheetOpen(false)} className="tap-target grid place-items-center rounded-full bg-secondary"><X className="h-5 w-5"/></button></div><p className="mb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">Transactions</p><div className="grid grid-cols-3 gap-2"><AddTransactionDialog initialType="expense"><ActionTile label="Expense" icon={TrendingDown} tone="negative"/></AddTransactionDialog><AddTransactionDialog initialType="income"><ActionTile label="Income" icon={TrendingUp} tone="positive"/></AddTransactionDialog><AddTransactionDialog initialType="transfer"><ActionTile label="Transfer" icon={ArrowLeftRight}/></AddTransactionDialog></div><p className="mb-2 mt-5 text-xs font-semibold uppercase tracking-wider text-muted-foreground">Accounts & planning</p><div className="space-y-2"><AccountDialog><ActionRow label="Add Account" icon={Wallet}/></AccountDialog><AddDebtDialog><ActionRow label="Add Debt" icon={TrendingDown}/></AddDebtDialog><AddGoalDialog><ActionRow label="Create Goal" icon={Target}/></AddGoalDialog></div></section></div>}
 </>;
}
function MobileLink({name,href,icon:Icon,active}:{name:string;href:string;icon:typeof Home;active:boolean}){return <Link href={href} className={cn("flex h-full flex-col items-center justify-center gap-0.5 text-[11px] font-medium",active?"text-primary":"text-muted-foreground")}><Icon className="h-5 w-5"/><span>{name}</span></Link>}
function ActionTile({label,icon:Icon,tone}:{label:string;icon:typeof Home;tone?:"negative"|"positive"}){return <button className="tap-target flex w-full flex-col items-center gap-2 rounded-2xl bg-secondary p-3 text-sm font-semibold"><span className={cn("grid h-9 w-9 place-items-center rounded-full",tone==="positive"?"bg-emerald-400/20 text-emerald-600":tone==="negative"?"bg-red-400/15 text-red-500":"bg-background text-foreground")}><Icon className="h-5 w-5"/></span>{label}</button>}
function ActionRow({label,icon:Icon}:{label:string;icon:typeof Home}){return <button className="tap-target flex w-full items-center gap-3 rounded-2xl bg-secondary px-4 py-3 text-left font-semibold"><span className="grid h-10 w-10 place-items-center rounded-xl bg-background text-primary"><Icon className="h-5 w-5"/></span>{label}</button>}
