import type { Metadata } from "next";
import { ContactCopy, LegalPage, type LegalSection } from "@/components/legal-page";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms governing use of the ZeroDebt financial planning application.",
  alternates: { canonical: "/terms" },
};

const sections: LegalSection[] = [
  { id: "acceptance", title: "Acceptance of these terms", content: <p>These Terms of Service govern your access to and use of ZeroDebt and its website. By creating an account or using the service, you agree to these terms and the Privacy Policy. If you do not agree, do not use the service.</p> },
  { id: "eligibility", title: "Eligibility", content: <p>You must be legally able to enter into these terms and meet the minimum age required for online services in your location. If you use ZeroDebt for another person or organization, you represent that you have authority to do so.</p> },
  { id: "accounts", title: "Account responsibility", content: <p>You are responsible for providing accurate account information, protecting access to your email, Google account, devices, and ZeroDebt session, and notifying support if you suspect unauthorized access. You are responsible for activity performed through your account unless applicable law provides otherwise.</p> },
  { id: "data", title: "Your financial data", content: <p>You retain responsibility for financial information you enter or confirm. You grant ZeroDebt permission to host, process, display, and calculate from that information only as needed to operate, secure, and improve the service. Verify important balances, dates, rates, and transactions before relying on them.</p> },
  { id: "service", title: "What ZeroDebt provides", content: <p>ZeroDebt is a personal financial organization and planning tool. Features may include debt tracking, Freedom Number and payoff calculations, payoff strategies, income and expense tracking, budgets, goals, Telegram Quick Entry, and account-aware explanations.</p> },
  { id: "estimates", title: "Debt payoff estimates", content: <p>Payoff dates, interest amounts, available balances, and related projections are estimates based on the information you provide and the calculation methods available in the product. Actual lender calculations, fees, rate changes, payment timing, new transactions, and other circumstances may produce different results.</p> },
  { id: "advice", title: "No professional advice", content: <p>ZeroDebt is not a bank, lender, broker, investment adviser, law firm, accounting firm, or tax adviser. The service provides general information and planning tools, not financial, legal, tax, or investment advice. Consider seeking a qualified professional for decisions requiring individualized advice.</p> },
  { id: "ai", title: "AI guidance", content: <p>Ask ZeroDebt may summarize or explain your recorded financial information. AI output can be incomplete or incorrect and should be checked against authoritative account records. AI guidance does not guarantee outcomes and does not replace professional advice. In the current read-only design, AI does not silently change your financial records.</p> },
  { id: "telegram", title: "Telegram integration", content: <p>If you connect Telegram, you are responsible for securing your Telegram account and reviewing transaction drafts before confirmation. Delivery may depend on Telegram and internet availability. Do not send passwords, authentication codes, or unrelated sensitive information to the bot.</p> },
  { id: "acceptable-use", title: "Acceptable use", content: <><p>You may not misuse ZeroDebt, interfere with its operation, attempt unauthorized access, evade usage limits, upload malicious material, use the service to violate law or another person’s rights, or reverse engineer protected portions except where applicable law permits it.</p><p>You may not use automated methods that create unreasonable load or attempt to extract another user’s information.</p></> },
  { id: "ip", title: "Intellectual property", content: <p>ZeroDebt and its software, branding, design, and original content are owned by ZeroDebt or its licensors and are protected by applicable intellectual-property laws. These terms give you a limited, revocable, non-transferable right to use the service for its intended purpose.</p> },
  { id: "availability", title: "Availability and changes", content: <p>We may maintain, change, suspend, or discontinue parts of the service. We aim to provide reasonable notice of material changes where practical, but uninterrupted availability is not guaranteed.</p> },
  { id: "third-parties", title: "Third-party services", content: <p>ZeroDebt depends on third-party services, including Supabase, Vercel, Google, Telegram, and an AI provider where enabled. Your use of those services may be subject to their terms. ZeroDebt is not responsible for third-party services beyond what applicable law requires.</p> },
  { id: "warranties", title: "Disclaimer of warranties", content: <p>To the extent permitted by applicable law, ZeroDebt is provided “as is” and “as available.” We disclaim implied warranties, including merchantability, fitness for a particular purpose, and non-infringement. Nothing in these terms excludes warranties or rights that cannot legally be excluded.</p> },
  { id: "liability", title: "Limitation of liability", content: <p>To the extent permitted by applicable law, ZeroDebt and its operators will not be liable for indirect, incidental, special, consequential, or punitive losses, or for lost profits, data, or opportunities arising from use of the service. Any limitation applies only to the extent legally permitted and does not exclude liability that cannot be limited.</p> },
  { id: "termination", title: "Suspension and termination", content: <p>You may stop using ZeroDebt at any time. We may suspend or terminate access when reasonably necessary to protect users or the service, address misuse, comply with law, or respond to a material breach of these terms. Where appropriate, we will provide notice or an opportunity to address the issue.</p> },
  { id: "deletion", title: "Account deletion", content: <p>Closing or deleting an account may permanently remove financial history, calculations, linked integrations, and conversations. Some limited records may be retained where required by law or reasonably necessary for security, fraud prevention, dispute resolution, or enforcing these terms.</p> },
  { id: "law", title: "Governing law", content: <p>The governing law and forum for these terms have not yet been finalized. They will be stated here before broad public launch. Mandatory consumer protections and rights in your location continue to apply where they cannot legally be waived.</p> },
  { id: "changes", title: "Changes to these terms", content: <p>We may update these terms as the service changes. We will update the “Last updated” date and provide additional notice of material changes when appropriate. Continued use after updated terms take effect means you accept them, where permitted by law.</p> },
  { id: "contact", title: "Contact", content: <ContactCopy /> },
];

export default function TermsPage() {
  return <LegalPage title="Terms of Service" summary="These terms set the rules for using ZeroDebt and explain the limits of its financial planning tools." updated="September 7, 2026" sections={sections} />;
}
