import {NextResponse} from 'next/server'; import {apiError,requireUser} from './api-auth';
export async function list(table:string,order='created_at'){const a=await requireUser();if('response'in a)return a.response;const{data,error}=await a.supabase.from(table).select('*').eq('user_id',a.user.id).order(order);return error?apiError('Unable to load data',500):NextResponse.json(data)}
export async function insert(table:string,row:Record<string,unknown>){const a=await requireUser();if('response'in a)return a.response;const{id:_,user_id:__,...safe}=row;const{data,error}=await a.supabase.from(table).insert({...safe,user_id:a.user.id}).select().single();return error?apiError('Unable to save data',400):NextResponse.json(data,{status:201})}
export async function update(table:string,id:string,row:Record<string,unknown>){const a=await requireUser();if('response'in a)return a.response;const{id:_,user_id:__,created_at:___,...safe}=row;const{data,error}=await a.supabase.from(table).update(safe).eq('id',id).eq('user_id',a.user.id).select().maybeSingle();return error?apiError('Unable to update data',400):data?NextResponse.json(data):apiError('Record not found',404)}
export async function remove(table:string,id:string){const a=await requireUser();if('response'in a)return a.response;const{data,error}=await a.supabase.from(table).delete().eq('id',id).eq('user_id',a.user.id).select('id').maybeSingle();return error?apiError('Unable to delete data',400):data?NextResponse.json({ok:true}):apiError('Record not found',404)}
export const mapAccount=(a:any)=>({name:a.name,institution:a.institution??'',type:a.type,currency:a.currency,opening_balance:a.openingBalance??0,color:a.color,is_default:!!a.isDefault,notes:a.notes??'',tag:a.tag??'',icon:a.icon??'wallet'});
export const mapDebt=(d:any)=>({name:d.name,original_amount:d.total,balance:d.balance,apr:d.rate??null,minimum_payment:d.minPayment??null,notes:d.notes??'',color:d.color});
export const mapIncome=(i:any)=>({name:i.name,type:i.type,status:i.status,currency:i.currency,expected_monthly:i.expectedMonthly??0,actual_this_month:i.actualThisMonth??0,notes:i.notes??'',color:i.color,icon:i.icon,linked_account_id:i.linkedAccountId||null});
export const mapGoal=(g:any)=>({name:g.name,target:g.target,saved:g.saved??0,deadline:g.deadline||null,description:g.description??'',category:g.category??'',notes:g.notes??''});
export const mapBudget=(e:any)=>({name:e.name,budgeted:e.budgeted,spent:e.spent??0,category:e.category??''});
export const mapTransaction=(t:any)=>({type:t.type,amount:t.amount,account_id:t.accountId,to_account_id:t.toAccountId||null,category:t.category??'',description:t.description??'',transaction_date:t.date,currency:t.currency,income_stream_id:t.incomeStreamId||null,notes:t.notes??''});
