import{calculatePayoff,freedomNumber,orderDebts,type Strategy}from'../debt-engine';import{calculateAvailableBalance}from'../utils';import type{FinanceSnapshot}from'./types';
type Debt={id:string;name:string;balance:number;original:number;apr:number|null;minimum:number};type Tx={type:string;amount:number;accountId:string;toAccountId:string|null;category:string;description:string;date:string;currency:string};
const monthKey=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;
export async function buildFinanceContext(supabase:any,userId:string):Promise<FinanceSnapshot>{
 const[prefs,profile,debtsR,accountsR,txR,goalsR]=await Promise.all([supabase.from('user_preferences').select('payoff_strategy').eq('user_id',userId).maybeSingle(),supabase.from('profiles').select('base_currency').eq('id',userId).single(),supabase.from('debts').select('id,name,original_amount,balance,apr,minimum_payment').eq('user_id',userId),supabase.from('accounts').select('id,name,type,currency,opening_balance').eq('user_id',userId),supabase.from('transactions').select('type,amount,account_id,to_account_id,category,description,transaction_date,currency').eq('user_id',userId).order('transaction_date',{ascending:false}).limit(250),supabase.from('goals').select('name,saved,target').eq('user_id',userId)]);if([profile,debtsR,accountsR,txR,goalsR].some(r=>r.error))throw new Error('context');
 const currency=profile.data?.base_currency||'INR',strategy:Strategy=prefs.data?.payoff_strategy==='snowball'?'snowball':'avalanche';
 const debts:Debt[]=(debtsR.data??[]).map((d:any)=>({id:d.id,name:d.name,balance:Number(d.balance),original:Number(d.original_amount),apr:d.apr==null?null:Number(d.apr),minimum:Number(d.minimum_payment??0)}));const accounts=(accountsR.data??[]).map((a:any)=>({id:a.id,name:a.name,type:a.type,currency:a.currency,openingBalance:Number(a.opening_balance)}));const transactions:Tx[]=(txR.data??[]).map((t:any)=>({type:t.type,amount:Number(t.amount),accountId:t.account_id,toAccountId:t.to_account_id,category:t.category||'Other',description:String(t.description||'').slice(0,80),date:t.transaction_date,currency:t.currency}));
 const now=new Date(),current=monthKey(now),previous=monthKey(new Date(now.getFullYear(),now.getMonth()-1,1)),inMonth=(t:Tx,key:string)=>String(t.date).slice(0,7)===key,monthly=transactions.filter((t:Tx)=>inMonth(t,current));const sum=(items:Tx[])=>items.reduce((total:number,t:Tx)=>total+t.amount,0),income=sum(monthly.filter((t:Tx)=>t.type==='income')),living=sum(monthly.filter((t:Tx)=>t.type==='expense'&&t.category!=='Debt Payment')),debtPayments=sum(monthly.filter((t:Tx)=>t.type==='expense'&&t.category==='Debt Payment')),payoffPower=Math.max(0,income-living);
 const engineDebts=debts.map((d:Debt)=>({id:d.id,balance:d.balance,apr:d.apr,minimumPayment:d.minimum})),payoff=calculatePayoff(engineDebts,payoffPower,strategy),available=calculateAvailableBalance(accounts,transactions,{aedToInr:25});const categories:string[]=[...new Set(transactions.filter((t:Tx)=>t.type==='expense'&&t.category!=='Debt Payment').map((t:Tx)=>t.category))],spending=categories.map((category:string)=>({category,current:sum(transactions.filter((t:Tx)=>t.type==='expense'&&t.category===category&&inMonth(t,current))),previous:sum(transactions.filter((t:Tx)=>t.type==='expense'&&t.category===category&&inMonth(t,previous)))})).filter(x=>x.current||x.previous).sort((a,b)=>b.current-a.current);
 const ordered=orderDebts(engineDebts,strategy),originalDebt=debts.reduce((total:number,d:Debt)=>total+d.original,0),freedom=freedomNumber(engineDebts),missing:string[]=[];if(!debts.length)missing.push('debts');if(!transactions.some((t:Tx)=>t.type==='income'))missing.push('income');if(debts.some((d:Debt)=>d.apr==null))missing.push('some debt APRs');if(!accounts.length)missing.push('accounts');
 return{currency,strategy,freedomNumber:freedom,originalDebt,paidAmount:Math.max(0,originalDebt-freedom),percentCleared:originalDebt?Math.max(0,(originalDebt-freedom)/originalDebt*100):0,monthlyMinimums:debts.reduce((total:number,d:Debt)=>total+d.minimum,0),availableBalance:available.balance,eligibleAccountCount:available.accountCount,monthlyIncome:income,livingExpenses:living,debtPayments,payoffPower,nextDebt:debts.find((d:Debt)=>d.id===ordered[0]?.id)?.name??null,debtFreeEstimate:payoff.debtFreeDate,debts:debts.map((d:Debt)=>({name:d.name,balance:d.balance,original:d.original,apr:d.apr,minimum:d.minimum})),spending,goals:(goalsR.data??[]).map((g:any)=>({name:g.name,saved:Number(g.saved),target:Number(g.target)})),recent:transactions.slice(0,12).map((t:Tx)=>({type:t.type,amount:t.amount,category:t.category,description:t.description,date:t.date})),missing};
}
export function simulateExtra(snapshot:FinanceSnapshot,extra:number){const debts=snapshot.debts.map((d,i)=>({id:String(i),balance:d.balance,apr:d.apr,minimumPayment:d.minimum})),current=calculatePayoff(debts,snapshot.payoffPower,snapshot.strategy),proposed=calculatePayoff(debts,snapshot.payoffPower+Math.max(0,extra),snapshot.strategy);return{currentMonths:current.months,proposedMonths:proposed.months,monthsSaved:current.months!=null&&proposed.months!=null?current.months-proposed.months:null,interestSaved:Math.max(0,current.totalInterest-proposed.totalInterest)}}
export function compareStrategies(snapshot:FinanceSnapshot){const debts=snapshot.debts.map((d,i)=>({id:String(i),balance:d.balance,apr:d.apr,minimumPayment:d.minimum}));return{avalanche:calculatePayoff(debts,snapshot.payoffPower,'avalanche'),snowball:calculatePayoff(debts,snapshot.payoffPower,'snowball')}}
