"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useFinanceStore } from "@/lib/store";
import { formatCurrency,getAccountBalance } from "@/lib/utils";
import { ArrowLeft,ArrowDownLeft,ArrowUpRight,ArrowRightLeft,Pencil,Wallet } from "lucide-react";
import * as React from "react";
import { AddTransactionDialog } from "@/components/add-transaction-dialog";
import { AccountDialog } from "@/components/add-account-dialog";
import { TransactionRow } from "@/components/transaction-actions";
export default function AccountDetail(){const {id}=useParams<{id:string}>();const {accounts,transactions,settings}=useFinanceStore();const account=accounts.find(a=>a.id===id);if(!account)return <main className="mobile-page"><p>Account not found.</p></main>;const txns=transactions.filter(t=>t.accountId===id||t.toAccountId===id);const now=new Date(),monthly=txns.filter(t=>{const d=new Date(t.date);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()});const income=monthly.filter(t=>t.type==="income").reduce((s,t)=>s+t.amount,0),spent=monthly.filter(t=>t.type==="expense").reduce((s,t)=>s+t.amount,0);return <main className="mobile-page"><header className="flex items-center gap-3"><Link href="/accounts" aria-label="Back" className="tap-target grid place-items-center rounded-full bg-secondary"><ArrowLeft className="h-5 w-5"/></Link><div className="min-w-0 flex-1"><h1 className="truncate text-2xl font-bold">{account.name}</h1><p className="truncate text-sm text-muted-foreground">{account.institution}</p></div><AccountDialog account={account}><button aria-label="Edit account" className="tap-target grid place-items-center rounded-full bg-secondary"><Pencil className="h-5 w-5"/></button></AccountDialog></header><section className="rounded-2xl bg-primary p-5 text-primary-foreground"><p className="text-xs uppercase tracking-wider opacity-70">Available balance</p><p className="tabular mt-3 text-4xl font-bold">{formatCurrency(getAccountBalance(id,accounts,transactions,settings),account.currency)}</p><div className="mt-6 grid grid-cols-2 gap-2"><div className="rounded-xl bg-white/10 p-3"><p className="text-xs opacity-70">Income this month</p><p className="tabular font-semibold">+{formatCurrency(income,account.currency)}</p></div><div className="rounded-xl bg-white/10 p-3"><p className="text-xs opacity-70">Expenses this month</p><p className="tabular font-semibold">-{formatCurrency(spent,account.currency)}</p></div></div></section><div className="grid grid-cols-3 gap-2"><AddTransactionDialog initialType="income" initialAccountId={id}><Action icon={ArrowDownLeft} label="Add income"/></AddTransactionDialog><AddTransactionDialog initialType="expense" initialAccountId={id}><Action icon={ArrowUpRight} label="Add expense"/></AddTransactionDialog><AddTransactionDialog initialType="transfer" initialAccountId={id}><Action icon={ArrowRightLeft} label="Transfer"/></AddTransactionDialog></div><section><h2 className="mb-3 text-xl font-semibold">Recent activity</h2><div className="mobile-card divide-y divide-border overflow-hidden">{txns.length?txns.slice(0,10).map(t=><TransactionRow key={t.id} transaction={t} variant="account" accountId={id}/>):<p className="p-6 text-center text-sm text-muted-foreground">No activity for this account yet.</p>}</div></section></main>}
const Action=React.forwardRef<HTMLButtonElement,React.ButtonHTMLAttributes<HTMLButtonElement>&{icon:typeof Wallet;label:string}>(({icon:Icon,label,...props},ref)=><button ref={ref} type="button" {...props} className="tap-target flex w-full flex-col items-center gap-2 rounded-2xl bg-card p-3 text-xs font-semibold shadow-sm"><Icon className="h-5 w-5 text-primary"/>{label}</button>);Action.displayName="AccountAction";
