import { requireAdminApi } from '@/lib/admin-auth';
import { getAnalyticsReport,getGoogleSnapshots } from '@/lib/admin-data';
import { csv } from '@/lib/analytics/csv';
const allowed=['registrations','acquisition','search-console-queries','search-console-pages','feature-adoption'] as const;
export async function GET(request:Request,{params}:{params:Promise<{report:string}>}){const auth=await requireAdminApi();if('response'in auth)return auth.response;const{name}=Object.fromEntries(new URL(request.url).searchParams),{report}=await params;if(!allowed.includes(report as never))return Response.json({error:{message:'Unknown export'}},{status:404});const query=Object.fromEntries(new URL(request.url).searchParams),{range,report:data}=await getAnalyticsReport(auth.db,query);let columns:string[]=[],rows:unknown[][]=[];
if(report==='registrations'){columns=['date','registrations','verified','total_users','total_verified','premium'];rows=data.registrationTrend.map(x=>[x.date,x.registered,x.verified,x.total,x.totalVerified,x.premium])}
else if(report==='feature-adoption'){columns=['feature','unique_users','percent_of_active_users','actions','previous_unique_users','previous_actions'];rows=data.featureAdoption.map(x=>[x.feature,x.users,data.active.selected?x.users/data.active.selected*100:0,x.actions,x.previousUsers,x.previousActions])}
else if(report==='acquisition'){columns=['source','medium','campaign','users','signup_completions'];rows=data.firstPartyAttribution.map(x=>[x.source,x.medium,x.campaign,x.users,x.signupCompletions])}
else{const snapshots=await getGoogleSnapshots(auth.db,range,'search_console'),kind=report.endsWith('queries')?'query':'page';columns=[kind,'date','clicks','impressions','ctr','position'];rows=snapshots.filter(x=>x.dimension_type===kind).map(x=>[x.dimension_value,x.metric_date,x.metrics.clicks,x.metrics.impressions,x.metrics.ctr,x.metrics.position])}
await auth.db.from('admin_audit_log').insert({actor_user_id:auth.identity.id,action:`${report}.exported`,target_type:'analytics_report',metadata:{filters:query,row_count:rows.length}});return new Response(csv(columns,rows),{headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="zerodebt-${name||report}-${range.from}-${range.to}.csv"`,'Cache-Control':'no-store'}})}
