"use client";
import Link from "next/link";
import { useFinanceStore } from "@/lib/store";
import { formatCurrency,getAccountBalance } from "@/lib/utils";
import { Wallet,Plus,ChevronRight,Landmark,CreditCard,PiggyBank } from "lucide-react";
import { AccountDialog } from "@/components/add-account-dialog";
const groups=[{label:"Cash & bank",types:["savings","current","cash","receivable"]},{label:"Investments",types:["investment"]},{label:"Credit & liabilities",types:["credit"]}] as const;
export default function Accounts(){const {accounts,transactions,settings}=useFinanceStore();const rows=accounts.map(a=>({...a,balance:getAccountBalance(a.id,accounts,transactions,settings)}));const total=rows.reduce((s,a)=>s+a.balance,0);return <main className="mobile-page"><header className="flex items-end justify-between gap-3"><div><h1 className="text-3xl font-bold">Accounts</h1><p className="text-muted-foreground">Your balances in one place</p></div><AccountDialog><button className="tap-target flex items-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground"><Plus className="h-4 w-4"/>Add</button></AccountDialog></header><section className="rounded-2xl bg-primary p-5 text-primary-foreground"><p className="text-xs uppercase tracking-wider opacity-70">Total balance</p><p className="tabular mt-3 text-4xl font-bold">{formatCurrency(total,settings.currency)}</p><p className="mt-4 text-sm opacity-75">Across {accounts.length} {accounts.length===1?"account":"accounts"}</p></section>{accounts.length===0?<section className="mobile-card p-7 text-center"><Wallet className="mx-auto h-9 w-9 text-primary"/><h2 className="mt-4 text-lg font-semibold">Add your first account</h2><p className="mt-2 text-sm text-muted-foreground">Track a bank account, cash wallet, investment, or credit balance.</p></section>:groups.map(group=>{const items=rows.filter(a=>(group.types as readonly string[]).includes(a.type));if(!items.length)return null;return <section key={group.label}><div className="mb-2 flex justify-between px-1"><h2 className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">{group.label}</h2><span className="tabular text-xs text-muted-foreground">{formatCurrency(items.reduce((s,a)=>s+a.balance,0),settings.currency)}</span></div><div className="mobile-card divide-y divide-border overflow-hidden">{items.map(a=><Link key={a.id} href={`/accounts/${a.id}`} className="flex min-h-[76px] items-center gap-3 px-4"><span className="grid h-11 w-11 place-items-center rounded-xl bg-secondary text-primary"><TypeIcon type={a.type}/></span><div className="min-w-0 flex-1"><p className="truncate font-semibold">{a.name}</p><p className="truncate text-sm text-muted-foreground">{a.institution} · {a.type}</p></div><div className="text-right"><p className="tabular font-semibold">{formatCurrency(a.balance,a.currency)}</p><p className="text-xs text-muted-foreground">{a.currency}</p></div><ChevronRight className="h-4 w-4 text-muted-foreground"/></Link>)}</div></section>})}</main>}
function TypeIcon({type}:{type:string}){if(type==="credit")return <CreditCard className="h-5 w-5"/>;if(type==="savings")return <PiggyBank className="h-5 w-5"/>;if(type==="current")return <Landmark className="h-5 w-5"/>;return <Wallet className="h-5 w-5"/>}
